// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type BatchPatchInstancesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Instances updated.
	BatchPatchInstancesResponse *components.BatchPatchInstancesResponse
}

func (b BatchPatchInstancesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BatchPatchInstancesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BatchPatchInstancesResponse) GetHTTPMeta() components.HTTPMetadata {
	if b == nil {
		return components.HTTPMetadata{}
	}
	return b.HTTPMeta
}

func (b *BatchPatchInstancesResponse) GetBatchPatchInstancesResponse() *components.BatchPatchInstancesResponse {
	if b == nil {
		return nil
	}
	return b.BatchPatchInstancesResponse
}
