// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type CreateInstanceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Instance created.
	InstanceResponse *components.InstanceResponse
}

func (c CreateInstanceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateInstanceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateInstanceResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateInstanceResponse) GetInstanceResponse() *components.InstanceResponse {
	if c == nil {
		return nil
	}
	return c.InstanceResponse
}
