// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type CreateWorkspaceHandlerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Workspace created.
	WorkspaceResponse *components.WorkspaceResponse
}

func (c CreateWorkspaceHandlerResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateWorkspaceHandlerResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateWorkspaceHandlerResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateWorkspaceHandlerResponse) GetWorkspaceResponse() *components.WorkspaceResponse {
	if c == nil {
		return nil
	}
	return c.WorkspaceResponse
}
