// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
	"github.com/sfcompute/sfc-go/optionalnullable"
)

type CreateCapacityTransferRequest struct {
	// Unique key for idempotent transfer creation.
	IdempotencyKey optionalnullable.OptionalNullable[string]  `header:"style=simple,explode=false,name=Idempotency-Key"`
	Body           components.V2CreateCapacityTransferRequest `request:"mediaType=application/json"`
}

func (c *CreateCapacityTransferRequest) GetIdempotencyKey() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}

func (c *CreateCapacityTransferRequest) GetBody() components.V2CreateCapacityTransferRequest {
	if c == nil {
		return components.V2CreateCapacityTransferRequest{}
	}
	return c.Body
}

type CreateCapacityTransferResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Capacity transfer accepted.
	V2CapacityTransferResponse *components.V2CapacityTransferResponse
}

func (c CreateCapacityTransferResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCapacityTransferResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateCapacityTransferResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateCapacityTransferResponse) GetV2CapacityTransferResponse() *components.V2CapacityTransferResponse {
	if c == nil {
		return nil
	}
	return c.V2CapacityTransferResponse
}
