// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type CreatePoolResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Pool created.
	PoolResponse *components.PoolResponse
}

func (c CreatePoolResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreatePoolResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreatePoolResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreatePoolResponse) GetPoolResponse() *components.PoolResponse {
	if c == nil {
		return nil
	}
	return c.PoolResponse
}
