// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type CreateCapacityResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Capacity created.
	CapacityResponse *components.CapacityResponse
}

func (c CreateCapacityResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCapacityResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateCapacityResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateCapacityResponse) GetCapacityResponse() *components.CapacityResponse {
	if c == nil {
		return nil
	}
	return c.CapacityResponse
}
