// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type CreateInstanceTemplateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Instance template created.
	InstanceTemplateResponse *components.InstanceTemplateResponse
}

func (c CreateInstanceTemplateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateInstanceTemplateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateInstanceTemplateResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateInstanceTemplateResponse) GetInstanceTemplateResponse() *components.InstanceTemplateResponse {
	if c == nil {
		return nil
	}
	return c.InstanceTemplateResponse
}
