// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/models/components"
)

type DeleteWorkspaceHandlerRequest struct {
	// Workspace name or ID
	Workspace string `pathParam:"style=simple,explode=false,name=workspace"`
}

func (d *DeleteWorkspaceHandlerRequest) GetWorkspace() string {
	if d == nil {
		return ""
	}
	return d.Workspace
}

type DeleteWorkspaceHandlerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteWorkspaceHandlerResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
