// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/models/components"
)

type DeleteInstanceRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteInstanceRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteInstanceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteInstanceResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
