// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go-sdk/internal/utils"
	"github.com/sfcompute/sfc-go-sdk/models/components"
)

type DeleteImageRequest struct {
	// Image ID, name, or resource path
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteImageRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteImageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Image deleted
	DeleteImageResponse *components.DeleteImageResponse
}

func (d DeleteImageResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteImageResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteImageResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteImageResponse) GetDeleteImageResponse() *components.DeleteImageResponse {
	if d == nil {
		return nil
	}
	return d.DeleteImageResponse
}
