// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type FetchInstanceRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (f *FetchInstanceRequest) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

type FetchInstanceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Instance details.
	InstanceResponse *components.InstanceResponse
}

func (f FetchInstanceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FetchInstanceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FetchInstanceResponse) GetHTTPMeta() components.HTTPMetadata {
	if f == nil {
		return components.HTTPMetadata{}
	}
	return f.HTTPMeta
}

func (f *FetchInstanceResponse) GetInstanceResponse() *components.InstanceResponse {
	if f == nil {
		return nil
	}
	return f.InstanceResponse
}
