// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type FetchOrderRequest struct {
	// Order ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (f *FetchOrderRequest) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

type FetchOrderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Order details.
	V2OrderResponse *components.V2OrderResponse
}

func (f FetchOrderResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FetchOrderResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FetchOrderResponse) GetHTTPMeta() components.HTTPMetadata {
	if f == nil {
		return components.HTTPMetadata{}
	}
	return f.HTTPMeta
}

func (f *FetchOrderResponse) GetV2OrderResponse() *components.V2OrderResponse {
	if f == nil {
		return nil
	}
	return f.V2OrderResponse
}
