// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type FetchCapacityTransferRequest struct {
	// Capacity transfer ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (f *FetchCapacityTransferRequest) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

type FetchCapacityTransferResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Capacity transfer details.
	V2CapacityTransferResponse *components.V2CapacityTransferResponse
}

func (f FetchCapacityTransferResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FetchCapacityTransferResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FetchCapacityTransferResponse) GetHTTPMeta() components.HTTPMetadata {
	if f == nil {
		return components.HTTPMetadata{}
	}
	return f.HTTPMeta
}

func (f *FetchCapacityTransferResponse) GetV2CapacityTransferResponse() *components.V2CapacityTransferResponse {
	if f == nil {
		return nil
	}
	return f.V2CapacityTransferResponse
}
