// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type FetchNodeExpand string

const (
	FetchNodeExpandCapacity   FetchNodeExpand = "capacity"
	FetchNodeExpandImage      FetchNodeExpand = "image"
	FetchNodeExpandDeployment FetchNodeExpand = "deployment"
)

func (e FetchNodeExpand) ToPointer() *FetchNodeExpand {
	return &e
}
func (e *FetchNodeExpand) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "capacity":
		fallthrough
	case "image":
		fallthrough
	case "deployment":
		*e = FetchNodeExpand(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FetchNodeExpand: %v", v)
	}
}

type FetchNodeRequest struct {
	ID     string            `pathParam:"style=simple,explode=false,name=id"`
	Expand []FetchNodeExpand `queryParam:"style=form,explode=true,name=expand"`
}

func (f FetchNodeRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FetchNodeRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FetchNodeRequest) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *FetchNodeRequest) GetExpand() []FetchNodeExpand {
	if f == nil {
		return nil
	}
	return f.Expand
}

type FetchNodeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Node details.
	NodeResponse *components.NodeResponse
}

func (f FetchNodeResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FetchNodeResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FetchNodeResponse) GetHTTPMeta() components.HTTPMetadata {
	if f == nil {
		return components.HTTPMetadata{}
	}
	return f.HTTPMeta
}

func (f *FetchNodeResponse) GetNodeResponse() *components.NodeResponse {
	if f == nil {
		return nil
	}
	return f.NodeResponse
}
