// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go-sdk/internal/utils"
	"github.com/sfcompute/sfc-go-sdk/models/components"
)

type GetNodeSSHRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetNodeSSHRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetNodeSSHResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// SSH connection details.
	NodeSSHInfo *components.NodeSSHInfo
}

func (g GetNodeSSHResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetNodeSSHResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetNodeSSHResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetNodeSSHResponse) GetNodeSSHInfo() *components.NodeSSHInfo {
	if g == nil {
		return nil
	}
	return g.NodeSSHInfo
}
