// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/sfcompute/sfc-go-sdk/internal/utils"
	"github.com/sfcompute/sfc-go-sdk/models/components"
)

type GetNodeLogsSortBy string

const (
	GetNodeLogsSortBySeqnum      GetNodeLogsSortBy = "seqnum"
	GetNodeLogsSortByMinusSeqnum GetNodeLogsSortBy = "-seqnum"
)

func (e GetNodeLogsSortBy) ToPointer() *GetNodeLogsSortBy {
	return &e
}
func (e *GetNodeLogsSortBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "seqnum":
		fallthrough
	case "-seqnum":
		*e = GetNodeLogsSortBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetNodeLogsSortBy: %v", v)
	}
}

type GetNodeLogsRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Return logs with `seqnum` less than or equal to this value.
	SeqnumBefore *int64 `queryParam:"style=form,explode=true,name=seqnum_before"`
	// Return logs with `seqnum` greater than or equal to this value.
	SeqnumAfter *int64 `queryParam:"style=form,explode=true,name=seqnum_after"`
	// Due to clock synchronization, some earlier log messages may have a realtime timestamp after this value.
	RealtimeTimestampBefore *int64 `queryParam:"style=form,explode=true,name=realtime_timestamp_before"`
	// Due to clock synchronization, some later log messages may have a realtime timestamp before this value.
	RealtimeTimestampAfter *int64             `queryParam:"style=form,explode=true,name=realtime_timestamp_after"`
	SortBy                 *GetNodeLogsSortBy `queryParam:"style=form,explode=true,name=sort_by"`
	Limit                  *int64             `default:"100" queryParam:"style=form,explode=true,name=limit"`
}

func (g GetNodeLogsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetNodeLogsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetNodeLogsRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetNodeLogsRequest) GetSeqnumBefore() *int64 {
	if g == nil {
		return nil
	}
	return g.SeqnumBefore
}

func (g *GetNodeLogsRequest) GetSeqnumAfter() *int64 {
	if g == nil {
		return nil
	}
	return g.SeqnumAfter
}

func (g *GetNodeLogsRequest) GetRealtimeTimestampBefore() *int64 {
	if g == nil {
		return nil
	}
	return g.RealtimeTimestampBefore
}

func (g *GetNodeLogsRequest) GetRealtimeTimestampAfter() *int64 {
	if g == nil {
		return nil
	}
	return g.RealtimeTimestampAfter
}

func (g *GetNodeLogsRequest) GetSortBy() *GetNodeLogsSortBy {
	if g == nil {
		return nil
	}
	return g.SortBy
}

func (g *GetNodeLogsRequest) GetLimit() *int64 {
	if g == nil {
		return nil
	}
	return g.Limit
}

type GetNodeLogsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Log chunks.
	NodeLogsResponse *components.NodeLogsResponse
}

func (g GetNodeLogsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetNodeLogsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetNodeLogsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetNodeLogsResponse) GetNodeLogsResponse() *components.NodeLogsResponse {
	if g == nil {
		return nil
	}
	return g.NodeLogsResponse
}
