// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/models/components"
)

type GetOrderPreviewResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Estimate result.
	V2OrderPreviewResponse *components.V2OrderPreviewResponse
}

func (g *GetOrderPreviewResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetOrderPreviewResponse) GetV2OrderPreviewResponse() *components.V2OrderPreviewResponse {
	if g == nil {
		return nil
	}
	return g.V2OrderPreviewResponse
}
