// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type GetProcurementRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetProcurementRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetProcurementResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Procurement details.
	ProcurementResponse *components.ProcurementResponse
}

func (g GetProcurementResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetProcurementResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetProcurementResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetProcurementResponse) GetProcurementResponse() *components.ProcurementResponse {
	if g == nil {
		return nil
	}
	return g.ProcurementResponse
}
