// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type ListInstanceSkuPropertyCatalogRequest struct {
	// Maximum number of results to return (1-200, default 50).
	Limit *int64 `default:"50" queryParam:"style=form,explode=true,name=limit"`
	// Cursor for forward pagination (from a previous response's `cursor` field).
	StartingAfter *string `queryParam:"style=form,explode=true,name=starting_after"`
	// Cursor for backward pagination.
	EndingBefore *string `queryParam:"style=form,explode=true,name=ending_before"`
}

func (l ListInstanceSkuPropertyCatalogRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListInstanceSkuPropertyCatalogRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListInstanceSkuPropertyCatalogRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListInstanceSkuPropertyCatalogRequest) GetStartingAfter() *string {
	if l == nil {
		return nil
	}
	return l.StartingAfter
}

func (l *ListInstanceSkuPropertyCatalogRequest) GetEndingBefore() *string {
	if l == nil {
		return nil
	}
	return l.EndingBefore
}

type ListInstanceSkuPropertyCatalogResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated property catalog.
	ListInstanceSkuPropertyCatalogResponse *components.ListInstanceSkuPropertyCatalogResponse

	Next func() (*ListInstanceSkuPropertyCatalogResponse, error)
}

func (l ListInstanceSkuPropertyCatalogResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListInstanceSkuPropertyCatalogResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListInstanceSkuPropertyCatalogResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListInstanceSkuPropertyCatalogResponse) GetListInstanceSkuPropertyCatalogResponse() *components.ListInstanceSkuPropertyCatalogResponse {
	if l == nil {
		return nil
	}
	return l.ListInstanceSkuPropertyCatalogResponse
}
