// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type ListCapacityTransfersRequest struct {
	// Filter by source or destination capacity (repeatable). Returns transfers where `from_capacity_id` or `to_capacity_id` is any of the supplied capacities.
	Capacity []string `queryParam:"style=form,explode=true,name=capacity"`
	// Filter by transfer status.
	Status *components.CapacityTransferStatus `queryParam:"style=form,explode=true,name=status"`
	Limit  *int64                             `default:"50" queryParam:"style=form,explode=true,name=limit"`
	// Set to the response's `cursor` to fetch the next page.
	StartingAfter *string `queryParam:"style=form,explode=true,name=starting_after"`
	// Set to the response's `cursor` to fetch the previous page.
	EndingBefore *string `queryParam:"style=form,explode=true,name=ending_before"`
}

func (l ListCapacityTransfersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCapacityTransfersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListCapacityTransfersRequest) GetCapacity() []string {
	if l == nil {
		return nil
	}
	return l.Capacity
}

func (l *ListCapacityTransfersRequest) GetStatus() *components.CapacityTransferStatus {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *ListCapacityTransfersRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListCapacityTransfersRequest) GetStartingAfter() *string {
	if l == nil {
		return nil
	}
	return l.StartingAfter
}

func (l *ListCapacityTransfersRequest) GetEndingBefore() *string {
	if l == nil {
		return nil
	}
	return l.EndingBefore
}

type ListCapacityTransfersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated list of capacity transfers.
	V2ListCapacityTransfersResponse *components.V2ListCapacityTransfersResponse

	Next func() (*ListCapacityTransfersResponse, error)
}

func (l ListCapacityTransfersResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCapacityTransfersResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListCapacityTransfersResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListCapacityTransfersResponse) GetV2ListCapacityTransfersResponse() *components.V2ListCapacityTransfersResponse {
	if l == nil {
		return nil
	}
	return l.V2ListCapacityTransfersResponse
}
