// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type ListOrderbookFillsRequest struct {
	// URL-safe `field[:op]:value` triples joined by `;`.
	Requirements *string `queryParam:"style=form,explode=true,name=requirements"`
	// Start of the delivery window.
	StartAt int64 `queryParam:"style=form,explode=true,name=start_at"`
	// End of the delivery window.
	EndAt int64 `queryParam:"style=form,explode=true,name=end_at"`
	// Lower bound on the contract's `created_at` (when the fill was recorded). Unix epoch seconds. Defaults to `now - 7d`; clamped to at most 90 days before `now` to bound scan cost.
	SinceAt *int64 `queryParam:"style=form,explode=true,name=since_at"`
	// Maximum results to return. Clamped to [1, 200]. Default 50.
	Limit *int64 `default:"50" queryParam:"style=form,explode=true,name=limit"`
	// Set to the response's `cursor` to fetch the next (older) page.
	StartingAfter *string `queryParam:"style=form,explode=true,name=starting_after"`
}

func (l ListOrderbookFillsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOrderbookFillsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListOrderbookFillsRequest) GetRequirements() *string {
	if l == nil {
		return nil
	}
	return l.Requirements
}

func (l *ListOrderbookFillsRequest) GetStartAt() int64 {
	if l == nil {
		return 0
	}
	return l.StartAt
}

func (l *ListOrderbookFillsRequest) GetEndAt() int64 {
	if l == nil {
		return 0
	}
	return l.EndAt
}

func (l *ListOrderbookFillsRequest) GetSinceAt() *int64 {
	if l == nil {
		return nil
	}
	return l.SinceAt
}

func (l *ListOrderbookFillsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListOrderbookFillsRequest) GetStartingAfter() *string {
	if l == nil {
		return nil
	}
	return l.StartingAfter
}

type ListOrderbookFillsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated list of fills.
	ListOrderbookFillsResponse *components.ListOrderbookFillsResponse
}

func (l ListOrderbookFillsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOrderbookFillsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListOrderbookFillsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListOrderbookFillsResponse) GetListOrderbookFillsResponse() *components.ListOrderbookFillsResponse {
	if l == nil {
		return nil
	}
	return l.ListOrderbookFillsResponse
}
