// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type ListProcurementsRequest struct {
	// Filter by workspace.
	Workspace     string   `queryParam:"style=form,explode=true,name=workspace"`
	Capacity      *string  `queryParam:"style=form,explode=true,name=capacity"`
	Limit         *int64   `default:"50" queryParam:"style=form,explode=true,name=limit"`
	StartingAfter *string  `queryParam:"style=form,explode=true,name=starting_after"`
	EndingBefore  *string  `queryParam:"style=form,explode=true,name=ending_before"`
	Expand        []string `queryParam:"style=form,explode=true,name=expand"`
}

func (l ListProcurementsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListProcurementsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListProcurementsRequest) GetWorkspace() string {
	if l == nil {
		return ""
	}
	return l.Workspace
}

func (l *ListProcurementsRequest) GetCapacity() *string {
	if l == nil {
		return nil
	}
	return l.Capacity
}

func (l *ListProcurementsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListProcurementsRequest) GetStartingAfter() *string {
	if l == nil {
		return nil
	}
	return l.StartingAfter
}

func (l *ListProcurementsRequest) GetEndingBefore() *string {
	if l == nil {
		return nil
	}
	return l.EndingBefore
}

func (l *ListProcurementsRequest) GetExpand() []string {
	if l == nil {
		return nil
	}
	return l.Expand
}

type ListProcurementsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated list of procurements.
	ListProcurementsResponse *components.ListProcurementsResponse

	Next func() (*ListProcurementsResponse, error)
}

func (l ListProcurementsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListProcurementsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListProcurementsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListProcurementsResponse) GetListProcurementsResponse() *components.ListProcurementsResponse {
	if l == nil {
		return nil
	}
	return l.ListProcurementsResponse
}
