// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type ListInstanceSkusRequest struct {
	// Maximum number of results to return (1-200, default 50).
	Limit *int64 `default:"50" queryParam:"style=form,explode=true,name=limit"`
	// Cursor for forward pagination (from a previous response's `cursor` field).
	StartingAfter *string `queryParam:"style=form,explode=true,name=starting_after"`
	// Cursor for backward pagination.
	EndingBefore *string `queryParam:"style=form,explode=true,name=ending_before"`
}

func (l ListInstanceSkusRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListInstanceSkusRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListInstanceSkusRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListInstanceSkusRequest) GetStartingAfter() *string {
	if l == nil {
		return nil
	}
	return l.StartingAfter
}

func (l *ListInstanceSkusRequest) GetEndingBefore() *string {
	if l == nil {
		return nil
	}
	return l.EndingBefore
}

type ListInstanceSkusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated list of instance SKUs.
	ListInstanceSkusResponse *components.ListInstanceSkusResponse

	Next func() (*ListInstanceSkusResponse, error)
}

func (l ListInstanceSkusResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListInstanceSkusResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListInstanceSkusResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListInstanceSkusResponse) GetListInstanceSkusResponse() *components.ListInstanceSkusResponse {
	if l == nil {
		return nil
	}
	return l.ListInstanceSkusResponse
}
