// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type ListNodesExpand string

const (
	ListNodesExpandCapacity   ListNodesExpand = "capacity"
	ListNodesExpandImage      ListNodesExpand = "image"
	ListNodesExpandDeployment ListNodesExpand = "deployment"
)

func (e ListNodesExpand) ToPointer() *ListNodesExpand {
	return &e
}
func (e *ListNodesExpand) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "capacity":
		fallthrough
	case "image":
		fallthrough
	case "deployment":
		*e = ListNodesExpand(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListNodesExpand: %v", v)
	}
}

type ListNodesRequest struct {
	// Filter by workspace.
	Workspace string `queryParam:"style=form,explode=true,name=workspace"`
	// Filter by node ID (repeatable).
	ID []string `queryParam:"style=form,explode=true,name=id"`
	// Filter by capacity.
	Capacity *string `queryParam:"style=form,explode=true,name=capacity"`
	// Filter by node status (repeatable).
	Status []components.NodeStatus `queryParam:"style=form,explode=true,name=status"`
	Limit  *int64                  `default:"50" queryParam:"style=form,explode=true,name=limit"`
	// Cursor for forward pagination (from a previous response's `cursor` field).
	StartingAfter *string `queryParam:"style=form,explode=true,name=starting_after"`
	// Cursor for backward pagination.
	EndingBefore *string `queryParam:"style=form,explode=true,name=ending_before"`
	// Additional fields to include in the response.
	Include []string `queryParam:"style=form,explode=true,name=include"`
	// Fields to expand with full objects instead of IDs.
	Expand []ListNodesExpand `queryParam:"style=form,explode=true,name=expand"`
	// Filter by tag key-value pair (repeatable). Format: `key=value` (the `=` between key and value must be percent-encoded in the URL).
	Tag []string `queryParam:"style=form,explode=true,name=tag"`
	// Filter by tag key existence (repeatable). Returns resources that have a tag with this key, regardless of the value.
	TagKey []string `queryParam:"style=form,explode=true,name=tag_key"`
}

func (l ListNodesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListNodesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListNodesRequest) GetWorkspace() string {
	if l == nil {
		return ""
	}
	return l.Workspace
}

func (l *ListNodesRequest) GetID() []string {
	if l == nil {
		return nil
	}
	return l.ID
}

func (l *ListNodesRequest) GetCapacity() *string {
	if l == nil {
		return nil
	}
	return l.Capacity
}

func (l *ListNodesRequest) GetStatus() []components.NodeStatus {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *ListNodesRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListNodesRequest) GetStartingAfter() *string {
	if l == nil {
		return nil
	}
	return l.StartingAfter
}

func (l *ListNodesRequest) GetEndingBefore() *string {
	if l == nil {
		return nil
	}
	return l.EndingBefore
}

func (l *ListNodesRequest) GetInclude() []string {
	if l == nil {
		return nil
	}
	return l.Include
}

func (l *ListNodesRequest) GetExpand() []ListNodesExpand {
	if l == nil {
		return nil
	}
	return l.Expand
}

func (l *ListNodesRequest) GetTag() []string {
	if l == nil {
		return nil
	}
	return l.Tag
}

func (l *ListNodesRequest) GetTagKey() []string {
	if l == nil {
		return nil
	}
	return l.TagKey
}

type ListNodesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated list of nodes.
	ListNodesResponse *components.ListNodesResponse

	Next func() (*ListNodesResponse, error)
}

func (l ListNodesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListNodesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListNodesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListNodesResponse) GetListNodesResponse() *components.ListNodesResponse {
	if l == nil {
		return nil
	}
	return l.ListNodesResponse
}
