// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type ListUserFeatureFlagsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Feature flags listed
	ListUserFeatureFlagsResponse *components.ListUserFeatureFlagsResponse
}

func (l ListUserFeatureFlagsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListUserFeatureFlagsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListUserFeatureFlagsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListUserFeatureFlagsResponse) GetListUserFeatureFlagsResponse() *components.ListUserFeatureFlagsResponse {
	if l == nil {
		return nil
	}
	return l.ListUserFeatureFlagsResponse
}
