// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type ListInstancesRequest struct {
	// Filter by workspace.
	Workspace string `queryParam:"style=form,explode=true,name=workspace"`
	// Filter by instance ID (repeatable).
	ID []string `queryParam:"style=form,explode=true,name=id"`
	// Filter by pool (repeatable). Instances on any of the given pools match.
	Pool []string `queryParam:"style=form,explode=true,name=pool"`
	// Filter by instance status (repeatable).
	Status []components.InstanceStatus `queryParam:"style=form,explode=true,name=status"`
	// Filter to instances created at or after this Unix timestamp (seconds).
	CreatedAfter *int64 `queryParam:"style=form,explode=true,name=created_after"`
	// Filter to instances created at or before this Unix timestamp (seconds).
	CreatedBefore *int64 `queryParam:"style=form,explode=true,name=created_before"`
	// Filter by instance SKU (repeatable). Instances on any of the given SKUs match.
	InstanceSku []string `queryParam:"style=form,explode=true,name=instance_sku"`
	Limit       *int64   `default:"50" queryParam:"style=form,explode=true,name=limit"`
	// Cursor for forward pagination (from a previous response's `cursor` field).
	StartingAfter *string `queryParam:"style=form,explode=true,name=starting_after"`
	// Cursor for backward pagination.
	EndingBefore *string `queryParam:"style=form,explode=true,name=ending_before"`
	// Additional fields to include in the response.
	Include []string `queryParam:"style=form,explode=true,name=include"`
	// Filter by tag key-value pair (repeatable). Format: `key=value` (the `=` between key and value must be percent-encoded in the URL).
	Tag []string `queryParam:"style=form,explode=true,name=tag"`
	// Filter by tag key existence (repeatable). Returns resources that have a tag with this key, regardless of the value.
	TagKey []string `queryParam:"style=form,explode=true,name=tag_key"`
}

func (l ListInstancesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListInstancesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListInstancesRequest) GetWorkspace() string {
	if l == nil {
		return ""
	}
	return l.Workspace
}

func (l *ListInstancesRequest) GetID() []string {
	if l == nil {
		return nil
	}
	return l.ID
}

func (l *ListInstancesRequest) GetPool() []string {
	if l == nil {
		return nil
	}
	return l.Pool
}

func (l *ListInstancesRequest) GetStatus() []components.InstanceStatus {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *ListInstancesRequest) GetCreatedAfter() *int64 {
	if l == nil {
		return nil
	}
	return l.CreatedAfter
}

func (l *ListInstancesRequest) GetCreatedBefore() *int64 {
	if l == nil {
		return nil
	}
	return l.CreatedBefore
}

func (l *ListInstancesRequest) GetInstanceSku() []string {
	if l == nil {
		return nil
	}
	return l.InstanceSku
}

func (l *ListInstancesRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListInstancesRequest) GetStartingAfter() *string {
	if l == nil {
		return nil
	}
	return l.StartingAfter
}

func (l *ListInstancesRequest) GetEndingBefore() *string {
	if l == nil {
		return nil
	}
	return l.EndingBefore
}

func (l *ListInstancesRequest) GetInclude() []string {
	if l == nil {
		return nil
	}
	return l.Include
}

func (l *ListInstancesRequest) GetTag() []string {
	if l == nil {
		return nil
	}
	return l.Tag
}

func (l *ListInstancesRequest) GetTagKey() []string {
	if l == nil {
		return nil
	}
	return l.TagKey
}

type ListInstancesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated list of instances.
	ListInstancesResponse *components.ListInstancesResponse

	Next func() (*ListInstancesResponse, error)
}

func (l ListInstancesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListInstancesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListInstancesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListInstancesResponse) GetListInstancesResponse() *components.ListInstancesResponse {
	if l == nil {
		return nil
	}
	return l.ListInstancesResponse
}
