// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type ListDeploymentsRequest struct {
	// Filter by workspace.
	Workspace string `queryParam:"style=form,explode=true,name=workspace"`
	// Filter by pool.
	Pool          *string `queryParam:"style=form,explode=true,name=pool"`
	Limit         *int64  `default:"50" queryParam:"style=form,explode=true,name=limit"`
	StartingAfter *string `queryParam:"style=form,explode=true,name=starting_after"`
	EndingBefore  *string `queryParam:"style=form,explode=true,name=ending_before"`
}

func (l ListDeploymentsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListDeploymentsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListDeploymentsRequest) GetWorkspace() string {
	if l == nil {
		return ""
	}
	return l.Workspace
}

func (l *ListDeploymentsRequest) GetPool() *string {
	if l == nil {
		return nil
	}
	return l.Pool
}

func (l *ListDeploymentsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListDeploymentsRequest) GetStartingAfter() *string {
	if l == nil {
		return nil
	}
	return l.StartingAfter
}

func (l *ListDeploymentsRequest) GetEndingBefore() *string {
	if l == nil {
		return nil
	}
	return l.EndingBefore
}

type ListDeploymentsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated list of deployments.
	ListDeploymentsResponse *components.ListDeploymentsResponse

	Next func() (*ListDeploymentsResponse, error)
}

func (l ListDeploymentsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListDeploymentsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListDeploymentsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListDeploymentsResponse) GetListDeploymentsResponse() *components.ListDeploymentsResponse {
	if l == nil {
		return nil
	}
	return l.ListDeploymentsResponse
}
