// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type ListPoolTransfersRequest struct {
	// Filter by source or destination pool (repeatable). Returns transfers where the source or destination pool is any of the supplied pools.
	Pool []string `queryParam:"style=form,explode=true,name=pool"`
	// Filter by transfer status.
	Status *components.V2PoolTransferStatus `queryParam:"style=form,explode=true,name=status"`
	Limit  *int64                           `default:"50" queryParam:"style=form,explode=true,name=limit"`
	// Set to the response's `cursor` to fetch the next page.
	StartingAfter *string `queryParam:"style=form,explode=true,name=starting_after"`
	// Set to the response's `cursor` to fetch the previous page.
	EndingBefore *string `queryParam:"style=form,explode=true,name=ending_before"`
}

func (l ListPoolTransfersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListPoolTransfersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListPoolTransfersRequest) GetPool() []string {
	if l == nil {
		return nil
	}
	return l.Pool
}

func (l *ListPoolTransfersRequest) GetStatus() *components.V2PoolTransferStatus {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *ListPoolTransfersRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListPoolTransfersRequest) GetStartingAfter() *string {
	if l == nil {
		return nil
	}
	return l.StartingAfter
}

func (l *ListPoolTransfersRequest) GetEndingBefore() *string {
	if l == nil {
		return nil
	}
	return l.EndingBefore
}

type ListPoolTransfersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated list of pool transfers.
	V2ListPoolTransfersResponse *components.V2ListPoolTransfersResponse

	Next func() (*ListPoolTransfersResponse, error)
}

func (l ListPoolTransfersResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListPoolTransfersResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListPoolTransfersResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListPoolTransfersResponse) GetV2ListPoolTransfersResponse() *components.V2ListPoolTransfersResponse {
	if l == nil {
		return nil
	}
	return l.V2ListPoolTransfersResponse
}
