// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type PatchWorkspaceHandlerRequest struct {
	// Workspace name or ID
	Workspace string                           `pathParam:"style=simple,explode=false,name=workspace"`
	Body      components.PatchWorkspaceRequest `request:"mediaType=application/json"`
}

func (p *PatchWorkspaceHandlerRequest) GetWorkspace() string {
	if p == nil {
		return ""
	}
	return p.Workspace
}

func (p *PatchWorkspaceHandlerRequest) GetBody() components.PatchWorkspaceRequest {
	if p == nil {
		return components.PatchWorkspaceRequest{}
	}
	return p.Body
}

type PatchWorkspaceHandlerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Workspace updated.
	WorkspaceResponse *components.WorkspaceResponse
}

func (p PatchWorkspaceHandlerResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatchWorkspaceHandlerResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PatchWorkspaceHandlerResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PatchWorkspaceHandlerResponse) GetWorkspaceResponse() *components.WorkspaceResponse {
	if p == nil {
		return nil
	}
	return p.WorkspaceResponse
}
