// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
	"github.com/sfcompute/sfc-go/optionalnullable"
)

type ReplaceInstanceRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Optional key that makes the request idempotent. Retries with the same key return the original replacement.
	IdempotencyKey optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=Idempotency-Key"`
	Body           components.ReplaceInstanceRequest         `request:"mediaType=application/json"`
}

func (r *ReplaceInstanceRequest) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *ReplaceInstanceRequest) GetIdempotencyKey() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.IdempotencyKey
}

func (r *ReplaceInstanceRequest) GetBody() components.ReplaceInstanceRequest {
	if r == nil {
		return components.ReplaceInstanceRequest{}
	}
	return r.Body
}

type ReplaceInstanceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Replacement instance created.
	InstanceResponse *components.InstanceResponse
}

func (r ReplaceInstanceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReplaceInstanceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReplaceInstanceResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReplaceInstanceResponse) GetInstanceResponse() *components.InstanceResponse {
	if r == nil {
		return nil
	}
	return r.InstanceResponse
}
