// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type RevokeImageRequest struct {
	// Image ID, name, or resource path
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (r *RevokeImageRequest) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

type RevokeImageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Image revoked
	ImageListEntry *components.ImageListEntry
}

func (r RevokeImageResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RevokeImageResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RevokeImageResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RevokeImageResponse) GetImageListEntry() *components.ImageListEntry {
	if r == nil {
		return nil
	}
	return r.ImageListEntry
}
