// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type TerminateInstanceRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (t *TerminateInstanceRequest) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

type TerminateInstanceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Instance terminated.
	InstanceResponse *components.InstanceResponse
}

func (t TerminateInstanceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TerminateInstanceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TerminateInstanceResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *TerminateInstanceResponse) GetInstanceResponse() *components.InstanceResponse {
	if t == nil {
		return nil
	}
	return t.InstanceResponse
}
