// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/models/components"
)

type UpdateInstanceRequest struct {
	ID   string                          `pathParam:"style=simple,explode=false,name=id"`
	Body components.PatchInstanceRequest `request:"mediaType=application/json"`
}

func (u *UpdateInstanceRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateInstanceRequest) GetBody() components.PatchInstanceRequest {
	if u == nil {
		return components.PatchInstanceRequest{}
	}
	return u.Body
}

type UpdateInstanceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Instance updated.
	InstanceResponse *components.InstanceResponse
}

func (u UpdateInstanceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateInstanceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateInstanceResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateInstanceResponse) GetInstanceResponse() *components.InstanceResponse {
	if u == nil {
		return nil
	}
	return u.InstanceResponse
}
