// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AutomationStatus string

const (
	AutomationStatusInfo    AutomationStatus = "info"
	AutomationStatusWarning AutomationStatus = "warning"
	AutomationStatusError   AutomationStatus = "error"
)

func (e AutomationStatus) ToPointer() *AutomationStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AutomationStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "info", "warning", "error":
			return true
		}
	}
	return false
}
