// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// BatchPatchInstanceEntry - One entry in a [`BatchPatchInstancesRequest`]: the instance to patch (`id`) and the fields to update. `priority_level` is the only field currently patchable here. To update name, tags, or other instance fields, use `PATCH /v2/instances/{id}`.
type BatchPatchInstanceEntry struct {
	// Accepts the canonical prefix below; additional legacy prefixes are aliased for read compatibility. Writes always emit the canonical form.
	ID string `json:"id"`
	// Instance priority — a relative ranking that determines which instances the system prefers to keep running when capacity is constrained. When a capacity's quota drops below its running-instance count, instances are terminated in priority order (lower first).
	//
	// Ordering: `yield < normal < preferred < critical`.
	PriorityLevel InstancePriority `json:"priority_level"`
}

func (b *BatchPatchInstanceEntry) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BatchPatchInstanceEntry) GetPriorityLevel() InstancePriority {
	if b == nil {
		return InstancePriority("")
	}
	return b.PriorityLevel
}
