// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CapacityTransferStatus string

const (
	CapacityTransferStatusPending  CapacityTransferStatus = "pending"
	CapacityTransferStatusExecuted CapacityTransferStatus = "executed"
	CapacityTransferStatusRejected CapacityTransferStatus = "rejected"
)

func (e CapacityTransferStatus) ToPointer() *CapacityTransferStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CapacityTransferStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "pending", "executed", "rejected":
			return true
		}
	}
	return false
}
