// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CapacitySummary struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (c *CapacitySummary) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CapacitySummary) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}
