// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/optionalnullable"
	"github.com/sfcompute/sfc-go/types"
)

type CapacityResponse struct {
	ID string `json:"id"`
	// A resource path for a capacity resource. Format: sfc:capacity:<account>:<workspace>:<name>.
	ResourcePath string `json:"resource_path"`
	Owner        string `json:"owner"`
	Workspace    string `json:"workspace"`
	WorkspaceID  string `json:"workspace_id"`
	Name         string `json:"name"`
	// Capacity kind determines what operations are allowed on a capacity.
	//
	// - `Market`: User-created capacities. - `Originating`: Provider capacities for selling compute. Cannot add compute   (buy orders/procurements). - `ReadOnly`: System-managed capacities used for legacy compute, bare metal   contracts, and other. Cannot be modified through the API.
	Kind CapacityKind `json:"kind"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	object             *string            `const:"capacity" json:"object"`
	AllocationSchedule AllocationSchedule `json:"allocation_schedule"`
	// Active procurements targeting this capacity.
	Procurements []ProcurementSummary `json:"procurements,omitzero"`
	// Active deployments targeting this capacity.
	Deployments []DeploymentSummary `json:"deployments,omitzero"`
	// Unix timestamp.
	CreatedAt int64                                                `json:"created_at"`
	Tags      optionalnullable.OptionalNullable[map[string]string] `json:"tags,omitzero"`
}

func (c CapacityResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CapacityResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CapacityResponse) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CapacityResponse) GetResourcePath() string {
	if c == nil {
		return ""
	}
	return c.ResourcePath
}

func (c *CapacityResponse) GetOwner() string {
	if c == nil {
		return ""
	}
	return c.Owner
}

func (c *CapacityResponse) GetWorkspace() string {
	if c == nil {
		return ""
	}
	return c.Workspace
}

func (c *CapacityResponse) GetWorkspaceID() string {
	if c == nil {
		return ""
	}
	return c.WorkspaceID
}

func (c *CapacityResponse) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CapacityResponse) GetKind() CapacityKind {
	if c == nil {
		return CapacityKind("")
	}
	return c.Kind
}

func (c *CapacityResponse) GetObject() *string {
	return types.Pointer("capacity")
}

func (c *CapacityResponse) GetAllocationSchedule() AllocationSchedule {
	if c == nil {
		return AllocationSchedule{}
	}
	return c.AllocationSchedule
}

func (c *CapacityResponse) GetProcurements() []ProcurementSummary {
	if c == nil {
		return nil
	}
	return c.Procurements
}

func (c *CapacityResponse) GetDeployments() []DeploymentSummary {
	if c == nil {
		return nil
	}
	return c.Deployments
}

func (c *CapacityResponse) GetCreatedAt() int64 {
	if c == nil {
		return 0
	}
	return c.CreatedAt
}

func (c *CapacityResponse) GetTags() optionalnullable.OptionalNullable[map[string]string] {
	if c == nil {
		return nil
	}
	return c.Tags
}
