// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CompleteUploadRequest - Complete a multipart image upload.
type CompleteUploadRequest struct {
	// Not verified on upload; used during node boot to verify integrity.
	Sha256 string `json:"sha256"`
}

func (c *CompleteUploadRequest) GetSha256() string {
	if c == nil {
		return ""
	}
	return c.Sha256
}
