// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/optionalnullable"
)

type CreateDeploymentRequest struct {
	Name optionalnullable.OptionalNullable[string] `json:"name,omitzero"`
	// A resource path like 'sfc:capacity:acme:prod:my-capacity' _or_ an ID. Resource paths are human-readable but not stable - they change when resources are renamed or moved. IDs are stable and permanent.
	Capacity string `json:"capacity"`
	// A resource path like 'sfc:instance_template:acme:prod:my-instance_template' _or_ an ID. Resource paths are human-readable but not stable - they change when resources are renamed or moved. IDs are stable and permanent.
	InstanceTemplate    string `json:"instance_template"`
	TargetInstanceCount int    `json:"target_instance_count"`
	// A name template using {{variable}} syntax. Available variables: {{adjective}} (~128 random adjectives), {{noun}} (~128 random nouns), {{nanoid(N)}} (N-character alphanumeric identifier, 1 ≤ N ≤ 21). The template must produce enough unique combinations to avoid collisions — equivalent to at least the default template {{adjective}}-{{noun}}-{{nanoid(6)}} (~1 quadrillion possibilities). Must start with an alphanumeric character. Resolved names are limited to 255 characters.
	InstanceNameTemplate *string `json:"instance_name_template,omitzero"`
}

func (c *CreateDeploymentRequest) GetName() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CreateDeploymentRequest) GetCapacity() string {
	if c == nil {
		return ""
	}
	return c.Capacity
}

func (c *CreateDeploymentRequest) GetInstanceTemplate() string {
	if c == nil {
		return ""
	}
	return c.InstanceTemplate
}

func (c *CreateDeploymentRequest) GetTargetInstanceCount() int {
	if c == nil {
		return 0
	}
	return c.TargetInstanceCount
}

func (c *CreateDeploymentRequest) GetInstanceNameTemplate() *string {
	if c == nil {
		return nil
	}
	return c.InstanceNameTemplate
}
