// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go-sdk/optionalnullable"
)

type CreateNodeTemplateRequest struct {
	Name optionalnullable.OptionalNullable[string] `json:"name,omitzero"`
	// A resource path like 'sfc:capacity:acme:prod:my-pool' _or_ an ID. Resource paths are human-readable but not stable - they change when resources are renamed or moved. IDs are stable and permanent.
	Workspace string `json:"workspace"`
	// A resource path like 'sfc:capacity:acme:prod:my-pool' _or_ an ID. Resource paths are human-readable but not stable - they change when resources are renamed or moved. IDs are stable and permanent.
	Image string `json:"image"`
	// Base64-encoded [cloud-init user data](https://cloudinit.readthedocs.io/en/latest/explanation/format/index.html). Maximum 64KB. Currently only the [User-Data Script](https://cloudinit.readthedocs.io/en/latest/explanation/format/user-data-script.html#user-data-script) format is supported.
	CloudInitUserData *string `json:"cloud_init_user_data,omitzero"`
}

func (c *CreateNodeTemplateRequest) GetName() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CreateNodeTemplateRequest) GetWorkspace() string {
	if c == nil {
		return ""
	}
	return c.Workspace
}

func (c *CreateNodeTemplateRequest) GetImage() string {
	if c == nil {
		return ""
	}
	return c.Image
}

func (c *CreateNodeTemplateRequest) GetCloudInitUserData() *string {
	if c == nil {
		return nil
	}
	return c.CloudInitUserData
}
