// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/optionalnullable"
)

type CreateInstanceRequest struct {
	Name optionalnullable.OptionalNullable[string] `json:"name,omitzero"`
	// A resource path like 'sfc:capacity:acme:prod:my-capacity' _or_ an ID. Resource paths are human-readable but not stable - they change when resources are renamed or moved. IDs are stable and permanent.
	Capacity string `json:"capacity"`
	// A resource path like 'sfc:image:acme:prod:my-image' _or_ an ID. Resource paths are human-readable but not stable - they change when resources are renamed or moved. IDs are stable and permanent.
	Image string `json:"image"`
	// Base64-encoded [cloud-init user data](https://cloudinit.readthedocs.io/en/latest/explanation/format/index.html). Maximum 64KB.
	CloudInitUserData *string                                              `json:"cloud_init_user_data,omitzero"`
	Tags              optionalnullable.OptionalNullable[map[string]string] `json:"tags,omitzero"`
}

func (c CreateInstanceRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateInstanceRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateInstanceRequest) GetName() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CreateInstanceRequest) GetCapacity() string {
	if c == nil {
		return ""
	}
	return c.Capacity
}

func (c *CreateInstanceRequest) GetImage() string {
	if c == nil {
		return ""
	}
	return c.Image
}

func (c *CreateInstanceRequest) GetCloudInitUserData() *string {
	if c == nil {
		return nil
	}
	return c.CloudInitUserData
}

func (c *CreateInstanceRequest) GetTags() optionalnullable.OptionalNullable[map[string]string] {
	if c == nil {
		return nil
	}
	return c.Tags
}
