// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/optionalnullable"
)

type CreateInstanceTemplateRequest struct {
	Name optionalnullable.OptionalNullable[string] `json:"name,omitzero"`
	// A resource path like 'sfc:workspace:acme:my-workspace' _or_ an ID. Resource paths are human-readable but not stable - they change when resources are renamed or moved. IDs are stable and permanent.
	Workspace string `json:"workspace"`
	// A resource path like 'sfc:image:acme:prod:my-image' _or_ an ID. Resource paths are human-readable but not stable - they change when resources are renamed or moved. IDs are stable and permanent.
	Image string `json:"image"`
	// Base64-encoded [cloud-init user data](https://cloudinit.readthedocs.io/en/latest/explanation/format/index.html). Maximum 64KB.
	CloudInitUserData *string `json:"cloud_init_user_data,omitzero"`
}

func (c *CreateInstanceTemplateRequest) GetName() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CreateInstanceTemplateRequest) GetWorkspace() string {
	if c == nil {
		return ""
	}
	return c.Workspace
}

func (c *CreateInstanceTemplateRequest) GetImage() string {
	if c == nil {
		return ""
	}
	return c.Image
}

func (c *CreateInstanceTemplateRequest) GetCloudInitUserData() *string {
	if c == nil {
		return nil
	}
	return c.CloudInitUserData
}
