// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go-sdk/internal/utils"
	"github.com/sfcompute/sfc-go-sdk/optionalnullable"
)

type CreateProcurementRequest struct {
	Name     optionalnullable.OptionalNullable[string] `json:"name,omitzero"`
	Target   ProcurementTarget                         `json:"target"`
	Capacity string                                    `json:"capacity"`
	// Price rate in dollars per node-hour.
	MinSellPriceDollarsPerNodeHour string `json:"min_sell_price_dollars_per_node_hour"`
	// Price rate in dollars per node-hour.
	MaxBuyPriceDollarsPerNodeHour string `json:"max_buy_price_dollars_per_node_hour"`
	// How far ahead (in minutes) the procurement buys and sells compute. Higher values secure compute further in advance but commit to longer windows that may need to be sold when scaling down, potentially at a loss. Lower values reduce waste but risk compute being unavailable. Orders are placed in 1-hour blocks, so the furthest hour is secured up to `managed_window_minutes - 60` minutes before it begins.
	ManagedWindowMinutes int `json:"managed_window_minutes"`
	// Enable/disable the procurement.
	Enabled *bool `default:"true" json:"enabled"`
}

func (c CreateProcurementRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateProcurementRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateProcurementRequest) GetName() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CreateProcurementRequest) GetTarget() ProcurementTarget {
	if c == nil {
		return ProcurementTarget{}
	}
	return c.Target
}

func (c *CreateProcurementRequest) GetCapacity() string {
	if c == nil {
		return ""
	}
	return c.Capacity
}

func (c *CreateProcurementRequest) GetMinSellPriceDollarsPerNodeHour() string {
	if c == nil {
		return ""
	}
	return c.MinSellPriceDollarsPerNodeHour
}

func (c *CreateProcurementRequest) GetMaxBuyPriceDollarsPerNodeHour() string {
	if c == nil {
		return ""
	}
	return c.MaxBuyPriceDollarsPerNodeHour
}

func (c *CreateProcurementRequest) GetManagedWindowMinutes() int {
	if c == nil {
		return 0
	}
	return c.ManagedWindowMinutes
}

func (c *CreateProcurementRequest) GetEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.Enabled
}
