// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/types"
)

type DeploymentResponse struct {
	ID string `json:"id"`
	// A resource path for a deployment resource. Format: sfc:deployment:<account>:<workspace>:<name>.
	ResourcePath string `json:"resource_path"`
	Owner        string `json:"owner"`
	Workspace    string `json:"workspace"`
	WorkspaceID  string `json:"workspace_id"`
	Name         string `json:"name"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	object              *string                 `const:"deployment" json:"object"`
	Capacity            CapacitySummary         `json:"capacity"`
	InstanceTemplate    InstanceTemplateSummary `json:"instance_template"`
	TargetInstanceCount int                     `json:"target_instance_count"`
	// A name template using {{variable}} syntax. Available variables: {{adjective}} (~128 random adjectives), {{noun}} (~128 random nouns), {{nanoid(N)}} (N-character alphanumeric identifier, 1 ≤ N ≤ 21). The template must produce enough unique combinations to avoid collisions — equivalent to at least the default template {{adjective}}-{{noun}}-{{nanoid(6)}} (~1 quadrillion possibilities). Must start with an alphanumeric character. Resolved names are limited to 255 characters.
	InstanceNameTemplate string               `json:"instance_name_template"`
	Status               ReconciliationStatus `json:"status"`
	// Unix timestamp.
	CreatedAt int64 `json:"created_at"`
	// Unix timestamp.
	UpdatedAt int64 `json:"updated_at"`
}

func (d DeploymentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeploymentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeploymentResponse) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeploymentResponse) GetResourcePath() string {
	if d == nil {
		return ""
	}
	return d.ResourcePath
}

func (d *DeploymentResponse) GetOwner() string {
	if d == nil {
		return ""
	}
	return d.Owner
}

func (d *DeploymentResponse) GetWorkspace() string {
	if d == nil {
		return ""
	}
	return d.Workspace
}

func (d *DeploymentResponse) GetWorkspaceID() string {
	if d == nil {
		return ""
	}
	return d.WorkspaceID
}

func (d *DeploymentResponse) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DeploymentResponse) GetObject() *string {
	return types.Pointer("deployment")
}

func (d *DeploymentResponse) GetCapacity() CapacitySummary {
	if d == nil {
		return CapacitySummary{}
	}
	return d.Capacity
}

func (d *DeploymentResponse) GetInstanceTemplate() InstanceTemplateSummary {
	if d == nil {
		return InstanceTemplateSummary{}
	}
	return d.InstanceTemplate
}

func (d *DeploymentResponse) GetTargetInstanceCount() int {
	if d == nil {
		return 0
	}
	return d.TargetInstanceCount
}

func (d *DeploymentResponse) GetInstanceNameTemplate() string {
	if d == nil {
		return ""
	}
	return d.InstanceNameTemplate
}

func (d *DeploymentResponse) GetStatus() ReconciliationStatus {
	if d == nil {
		return ReconciliationStatus{}
	}
	return d.Status
}

func (d *DeploymentResponse) GetCreatedAt() int64 {
	if d == nil {
		return 0
	}
	return d.CreatedAt
}

func (d *DeploymentResponse) GetUpdatedAt() int64 {
	if d == nil {
		return 0
	}
	return d.UpdatedAt
}
