// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeploymentSummary struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (d *DeploymentSummary) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeploymentSummary) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}
