// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"github.com/sfcompute/sfc-go/internal/utils"
)

type ExpandableListDeploymentIDDeploymentSummary struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (e ExpandableListDeploymentIDDeploymentSummary) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExpandableListDeploymentIDDeploymentSummary) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExpandableListDeploymentIDDeploymentSummary) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *ExpandableListDeploymentIDDeploymentSummary) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

type ExpandableListDeploymentIDDeploymentSummaryUnionType string

const (
	ExpandableListDeploymentIDDeploymentSummaryUnionTypeArrayOfStr                                         ExpandableListDeploymentIDDeploymentSummaryUnionType = "arrayOfStr"
	ExpandableListDeploymentIDDeploymentSummaryUnionTypeArrayOfExpandableListDeploymentIDDeploymentSummary ExpandableListDeploymentIDDeploymentSummaryUnionType = "arrayOfExpandableListDeploymentIDDeploymentSummary"
	ExpandableListDeploymentIDDeploymentSummaryUnionTypeUnknown                                            ExpandableListDeploymentIDDeploymentSummaryUnionType = "Unknown"
)

// ExpandableListDeploymentIDDeploymentSummaryUnion - Array of IDs (default) or expanded summaries when using expand parameter
type ExpandableListDeploymentIDDeploymentSummaryUnion struct {
	ArrayOfStr                                         []string                                      `queryParam:"inline" union:"member"`
	ArrayOfExpandableListDeploymentIDDeploymentSummary []ExpandableListDeploymentIDDeploymentSummary `queryParam:"inline" union:"member"`
	UnknownRaw                                         json.RawMessage                               `json:"-" union:"unknown"`

	Type ExpandableListDeploymentIDDeploymentSummaryUnionType
}

func CreateExpandableListDeploymentIDDeploymentSummaryUnionArrayOfStr(arrayOfStr []string) ExpandableListDeploymentIDDeploymentSummaryUnion {
	typ := ExpandableListDeploymentIDDeploymentSummaryUnionTypeArrayOfStr

	return ExpandableListDeploymentIDDeploymentSummaryUnion{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func CreateExpandableListDeploymentIDDeploymentSummaryUnionArrayOfExpandableListDeploymentIDDeploymentSummary(arrayOfExpandableListDeploymentIDDeploymentSummary []ExpandableListDeploymentIDDeploymentSummary) ExpandableListDeploymentIDDeploymentSummaryUnion {
	typ := ExpandableListDeploymentIDDeploymentSummaryUnionTypeArrayOfExpandableListDeploymentIDDeploymentSummary

	return ExpandableListDeploymentIDDeploymentSummaryUnion{
		ArrayOfExpandableListDeploymentIDDeploymentSummary: arrayOfExpandableListDeploymentIDDeploymentSummary,
		Type: typ,
	}
}

func CreateExpandableListDeploymentIDDeploymentSummaryUnionUnknown(raw json.RawMessage) ExpandableListDeploymentIDDeploymentSummaryUnion {
	return ExpandableListDeploymentIDDeploymentSummaryUnion{
		UnknownRaw: raw,
		Type:       ExpandableListDeploymentIDDeploymentSummaryUnionTypeUnknown,
	}
}

func (u ExpandableListDeploymentIDDeploymentSummaryUnion) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u ExpandableListDeploymentIDDeploymentSummaryUnion) IsUnknown() bool {
	return u.Type == ExpandableListDeploymentIDDeploymentSummaryUnionTypeUnknown
}

func (u *ExpandableListDeploymentIDDeploymentSummaryUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ExpandableListDeploymentIDDeploymentSummaryUnionTypeArrayOfStr,
			Value: arrayOfStr,
		})
	}

	var arrayOfExpandableListDeploymentIDDeploymentSummary []ExpandableListDeploymentIDDeploymentSummary = []ExpandableListDeploymentIDDeploymentSummary{}
	if err := utils.UnmarshalJSON(data, &arrayOfExpandableListDeploymentIDDeploymentSummary, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ExpandableListDeploymentIDDeploymentSummaryUnionTypeArrayOfExpandableListDeploymentIDDeploymentSummary,
			Value: arrayOfExpandableListDeploymentIDDeploymentSummary,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ExpandableListDeploymentIDDeploymentSummaryUnionTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ExpandableListDeploymentIDDeploymentSummaryUnionTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ExpandableListDeploymentIDDeploymentSummaryUnionType)
	switch best.Type {
	case ExpandableListDeploymentIDDeploymentSummaryUnionTypeArrayOfStr:
		u.ArrayOfStr = best.Value.([]string)
		return nil
	case ExpandableListDeploymentIDDeploymentSummaryUnionTypeArrayOfExpandableListDeploymentIDDeploymentSummary:
		u.ArrayOfExpandableListDeploymentIDDeploymentSummary = best.Value.([]ExpandableListDeploymentIDDeploymentSummary)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = ExpandableListDeploymentIDDeploymentSummaryUnionTypeUnknown
	return nil
}

func (u ExpandableListDeploymentIDDeploymentSummaryUnion) MarshalJSON() ([]byte, error) {
	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	if u.ArrayOfExpandableListDeploymentIDDeploymentSummary != nil {
		return utils.MarshalJSON(u.ArrayOfExpandableListDeploymentIDDeploymentSummary, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type ExpandableListDeploymentIDDeploymentSummaryUnion: all fields are null")
}
