// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"github.com/sfcompute/sfc-go/internal/utils"
)

type ExpandableListProcurementIDProcurementSummary struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (e ExpandableListProcurementIDProcurementSummary) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExpandableListProcurementIDProcurementSummary) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExpandableListProcurementIDProcurementSummary) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *ExpandableListProcurementIDProcurementSummary) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

type ExpandableListProcurementIDProcurementSummaryUnionType string

const (
	ExpandableListProcurementIDProcurementSummaryUnionTypeArrayOfStr                                           ExpandableListProcurementIDProcurementSummaryUnionType = "arrayOfStr"
	ExpandableListProcurementIDProcurementSummaryUnionTypeArrayOfExpandableListProcurementIDProcurementSummary ExpandableListProcurementIDProcurementSummaryUnionType = "arrayOfExpandableListProcurementIDProcurementSummary"
	ExpandableListProcurementIDProcurementSummaryUnionTypeUnknown                                              ExpandableListProcurementIDProcurementSummaryUnionType = "Unknown"
)

// ExpandableListProcurementIDProcurementSummaryUnion - Array of IDs (default) or expanded summaries when using expand parameter
type ExpandableListProcurementIDProcurementSummaryUnion struct {
	ArrayOfStr                                           []string                                        `queryParam:"inline" union:"member"`
	ArrayOfExpandableListProcurementIDProcurementSummary []ExpandableListProcurementIDProcurementSummary `queryParam:"inline" union:"member"`
	UnknownRaw                                           json.RawMessage                                 `json:"-" union:"unknown"`

	Type ExpandableListProcurementIDProcurementSummaryUnionType
}

func CreateExpandableListProcurementIDProcurementSummaryUnionArrayOfStr(arrayOfStr []string) ExpandableListProcurementIDProcurementSummaryUnion {
	typ := ExpandableListProcurementIDProcurementSummaryUnionTypeArrayOfStr

	return ExpandableListProcurementIDProcurementSummaryUnion{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func CreateExpandableListProcurementIDProcurementSummaryUnionArrayOfExpandableListProcurementIDProcurementSummary(arrayOfExpandableListProcurementIDProcurementSummary []ExpandableListProcurementIDProcurementSummary) ExpandableListProcurementIDProcurementSummaryUnion {
	typ := ExpandableListProcurementIDProcurementSummaryUnionTypeArrayOfExpandableListProcurementIDProcurementSummary

	return ExpandableListProcurementIDProcurementSummaryUnion{
		ArrayOfExpandableListProcurementIDProcurementSummary: arrayOfExpandableListProcurementIDProcurementSummary,
		Type: typ,
	}
}

func CreateExpandableListProcurementIDProcurementSummaryUnionUnknown(raw json.RawMessage) ExpandableListProcurementIDProcurementSummaryUnion {
	return ExpandableListProcurementIDProcurementSummaryUnion{
		UnknownRaw: raw,
		Type:       ExpandableListProcurementIDProcurementSummaryUnionTypeUnknown,
	}
}

func (u ExpandableListProcurementIDProcurementSummaryUnion) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u ExpandableListProcurementIDProcurementSummaryUnion) IsUnknown() bool {
	return u.Type == ExpandableListProcurementIDProcurementSummaryUnionTypeUnknown
}

func (u *ExpandableListProcurementIDProcurementSummaryUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ExpandableListProcurementIDProcurementSummaryUnionTypeArrayOfStr,
			Value: arrayOfStr,
		})
	}

	var arrayOfExpandableListProcurementIDProcurementSummary []ExpandableListProcurementIDProcurementSummary = []ExpandableListProcurementIDProcurementSummary{}
	if err := utils.UnmarshalJSON(data, &arrayOfExpandableListProcurementIDProcurementSummary, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ExpandableListProcurementIDProcurementSummaryUnionTypeArrayOfExpandableListProcurementIDProcurementSummary,
			Value: arrayOfExpandableListProcurementIDProcurementSummary,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ExpandableListProcurementIDProcurementSummaryUnionTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ExpandableListProcurementIDProcurementSummaryUnionTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ExpandableListProcurementIDProcurementSummaryUnionType)
	switch best.Type {
	case ExpandableListProcurementIDProcurementSummaryUnionTypeArrayOfStr:
		u.ArrayOfStr = best.Value.([]string)
		return nil
	case ExpandableListProcurementIDProcurementSummaryUnionTypeArrayOfExpandableListProcurementIDProcurementSummary:
		u.ArrayOfExpandableListProcurementIDProcurementSummary = best.Value.([]ExpandableListProcurementIDProcurementSummary)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = ExpandableListProcurementIDProcurementSummaryUnionTypeUnknown
	return nil
}

func (u ExpandableListProcurementIDProcurementSummaryUnion) MarshalJSON() ([]byte, error) {
	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	if u.ArrayOfExpandableListProcurementIDProcurementSummary != nil {
		return utils.MarshalJSON(u.ArrayOfExpandableListProcurementIDProcurementSummary, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type ExpandableListProcurementIDProcurementSummaryUnion: all fields are null")
}
