// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go-sdk/internal/utils"
	"github.com/sfcompute/sfc-go-sdk/optionalnullable"
	"github.com/sfcompute/sfc-go-sdk/types"
)

type ImageListEntry struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	object       *string           `const:"image" json:"object"`
	ID           string            `json:"id"`
	Name         string            `json:"name"`
	Owner        string            `json:"owner"`
	Workspace    string            `json:"workspace"`
	ResourcePath string            `json:"resource_path"`
	UploadStatus ImageUploadStatus `json:"upload_status"`
	// Unix timestamp.
	CreatedAt int64                                     `json:"created_at"`
	Provider  optionalnullable.OptionalNullable[string] `json:"provider,omitzero"`
	Sha256    optionalnullable.OptionalNullable[string] `json:"sha256,omitzero"`
}

func (i ImageListEntry) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ImageListEntry) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *ImageListEntry) GetObject() *string {
	return types.Pointer("image")
}

func (i *ImageListEntry) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *ImageListEntry) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *ImageListEntry) GetOwner() string {
	if i == nil {
		return ""
	}
	return i.Owner
}

func (i *ImageListEntry) GetWorkspace() string {
	if i == nil {
		return ""
	}
	return i.Workspace
}

func (i *ImageListEntry) GetResourcePath() string {
	if i == nil {
		return ""
	}
	return i.ResourcePath
}

func (i *ImageListEntry) GetUploadStatus() ImageUploadStatus {
	if i == nil {
		return ImageUploadStatus("")
	}
	return i.UploadStatus
}

func (i *ImageListEntry) GetCreatedAt() int64 {
	if i == nil {
		return 0
	}
	return i.CreatedAt
}

func (i *ImageListEntry) GetProvider() optionalnullable.OptionalNullable[string] {
	if i == nil {
		return nil
	}
	return i.Provider
}

func (i *ImageListEntry) GetSha256() optionalnullable.OptionalNullable[string] {
	if i == nil {
		return nil
	}
	return i.Sha256
}
