// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go-sdk/internal/utils"
	"github.com/sfcompute/sfc-go-sdk/optionalnullable"
	"github.com/sfcompute/sfc-go-sdk/types"
)

type ImageUploadResponse struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	object       *string                                   `const:"image" json:"object"`
	ID           string                                    `json:"id"`
	Name         string                                    `json:"name"`
	Owner        string                                    `json:"owner"`
	Workspace    string                                    `json:"workspace"`
	ResourcePath string                                    `json:"resource_path"`
	UploadStatus ImageUploadStatus                         `json:"upload_status"`
	Sha256       optionalnullable.OptionalNullable[string] `json:"sha256,omitzero"`
	// Unix timestamp.
	CreatedAt int64 `json:"created_at"`
}

func (i ImageUploadResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ImageUploadResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *ImageUploadResponse) GetObject() *string {
	return types.Pointer("image")
}

func (i *ImageUploadResponse) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *ImageUploadResponse) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *ImageUploadResponse) GetOwner() string {
	if i == nil {
		return ""
	}
	return i.Owner
}

func (i *ImageUploadResponse) GetWorkspace() string {
	if i == nil {
		return ""
	}
	return i.Workspace
}

func (i *ImageUploadResponse) GetResourcePath() string {
	if i == nil {
		return ""
	}
	return i.ResourcePath
}

func (i *ImageUploadResponse) GetUploadStatus() ImageUploadStatus {
	if i == nil {
		return ImageUploadStatus("")
	}
	return i.UploadStatus
}

func (i *ImageUploadResponse) GetSha256() optionalnullable.OptionalNullable[string] {
	if i == nil {
		return nil
	}
	return i.Sha256
}

func (i *ImageUploadResponse) GetCreatedAt() int64 {
	if i == nil {
		return 0
	}
	return i.CreatedAt
}
