// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type InstanceTemplateSummary struct {
	// Accepts the canonical prefix below; additional legacy prefixes are aliased for read compatibility. Writes always emit the canonical form.
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (i *InstanceTemplateSummary) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *InstanceTemplateSummary) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}
