// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/optionalnullable"
)

// InstanceSkuEnumerationValue - One allowed value for an enumeration-typed property key.
type InstanceSkuEnumerationValue struct {
	Name string `json:"name"`
	// Human-readable display name.
	DisplayName       string                                    `json:"display_name"`
	Description       string                                    `json:"description"`
	DocumentationLink optionalnullable.OptionalNullable[string] `json:"documentation_link,omitzero"`
	// Unix timestamp.
	StableAt     int64                                    `json:"stable_at"`
	DeprecatedAt optionalnullable.OptionalNullable[int64] `json:"deprecated_at,omitzero"`
	// Migration guidance shown when the value is deprecated.
	DeprecationInfo optionalnullable.OptionalNullable[string] `json:"deprecation_info,omitzero"`
}

func (i InstanceSkuEnumerationValue) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InstanceSkuEnumerationValue) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InstanceSkuEnumerationValue) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *InstanceSkuEnumerationValue) GetDisplayName() string {
	if i == nil {
		return ""
	}
	return i.DisplayName
}

func (i *InstanceSkuEnumerationValue) GetDescription() string {
	if i == nil {
		return ""
	}
	return i.Description
}

func (i *InstanceSkuEnumerationValue) GetDocumentationLink() optionalnullable.OptionalNullable[string] {
	if i == nil {
		return nil
	}
	return i.DocumentationLink
}

func (i *InstanceSkuEnumerationValue) GetStableAt() int64 {
	if i == nil {
		return 0
	}
	return i.StableAt
}

func (i *InstanceSkuEnumerationValue) GetDeprecatedAt() optionalnullable.OptionalNullable[int64] {
	if i == nil {
		return nil
	}
	return i.DeprecatedAt
}

func (i *InstanceSkuEnumerationValue) GetDeprecationInfo() optionalnullable.OptionalNullable[string] {
	if i == nil {
		return nil
	}
	return i.DeprecationInfo
}
