// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/optionalnullable"
)

type InstanceSSHInfo struct {
	Hostname                  string                                   `json:"hostname"`
	Port                      int64                                    `json:"port"`
	HostKeys                  []InstanceSSHHostKey                     `json:"host_keys"`
	LastSuccessfulKeyUpdateAt optionalnullable.OptionalNullable[int64] `json:"last_successful_key_update_at,omitzero"`
	LastAttemptedKeyUpdateAt  optionalnullable.OptionalNullable[int64] `json:"last_attempted_key_update_at,omitzero"`
}

func (i *InstanceSSHInfo) GetHostname() string {
	if i == nil {
		return ""
	}
	return i.Hostname
}

func (i *InstanceSSHInfo) GetPort() int64 {
	if i == nil {
		return 0
	}
	return i.Port
}

func (i *InstanceSSHInfo) GetHostKeys() []InstanceSSHHostKey {
	if i == nil {
		return []InstanceSSHHostKey{}
	}
	return i.HostKeys
}

func (i *InstanceSSHInfo) GetLastSuccessfulKeyUpdateAt() optionalnullable.OptionalNullable[int64] {
	if i == nil {
		return nil
	}
	return i.LastSuccessfulKeyUpdateAt
}

func (i *InstanceSSHInfo) GetLastAttemptedKeyUpdateAt() optionalnullable.OptionalNullable[int64] {
	if i == nil {
		return nil
	}
	return i.LastAttemptedKeyUpdateAt
}
