// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/optionalnullable"
	"github.com/sfcompute/sfc-go/types"
)

type InstanceResponse struct {
	// Accepts the canonical prefix below; additional legacy prefixes are aliased for read compatibility. Writes always emit the canonical form.
	ID string `json:"id"`
	// A resource path for a instance resource. Format: sfc:instance:<account>:<workspace>:<name>.
	ResourcePath string `json:"resource_path"`
	Owner        string `json:"owner"`
	Workspace    string `json:"workspace"`
	WorkspaceID  string `json:"workspace_id"`
	Name         string `json:"name"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	object *string `const:"instance" json:"object"`
	// `awaiting_allocation` when waiting for compute allocation on its capacity, `running` once assigned and the physical machine is running (still takes time for the image to be downloaded and booted), `terminated` when stopped by the user or after running out of allocation, `failed` on hardware fault.
	Status      InstanceStatus                                        `json:"status"`
	InstanceSku optionalnullable.OptionalNullable[InstanceSkuSummary] `json:"instance_sku,omitzero"`
	Capacity    CapacitySummary                                       `json:"capacity"`
	// A pool referenced by id and name.
	Pool PoolSummary `json:"pool"`
	// Unix timestamp.
	CreatedAt  int64                                                `json:"created_at"`
	Image      ImageSummary                                         `json:"image"`
	Deployment optionalnullable.OptionalNullable[DeploymentSummary] `json:"deployment,omitzero"`
	// Whether cloud-init user data is configured for this instance.
	CloudInitUserDataUsed bool `json:"cloud_init_user_data_used"`
	// Base64-encoded [cloud-init user data](https://cloudinit.readthedocs.io/en/latest/explanation/format/index.html).
	CloudInitUserData  *string                                              `json:"cloud_init_user_data,omitzero"`
	Tags               optionalnullable.OptionalNullable[map[string]string] `json:"tags,omitzero"`
	ExpectedShutdownAt optionalnullable.OptionalNullable[int64]             `json:"expected_shutdown_at,omitzero"`
	PriorityLevel      optionalnullable.OptionalNullable[InstancePriority]  `json:"priority_level,omitzero"`
}

func (i InstanceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InstanceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InstanceResponse) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *InstanceResponse) GetResourcePath() string {
	if i == nil {
		return ""
	}
	return i.ResourcePath
}

func (i *InstanceResponse) GetOwner() string {
	if i == nil {
		return ""
	}
	return i.Owner
}

func (i *InstanceResponse) GetWorkspace() string {
	if i == nil {
		return ""
	}
	return i.Workspace
}

func (i *InstanceResponse) GetWorkspaceID() string {
	if i == nil {
		return ""
	}
	return i.WorkspaceID
}

func (i *InstanceResponse) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *InstanceResponse) GetObject() *string {
	return types.Pointer("instance")
}

func (i *InstanceResponse) GetStatus() InstanceStatus {
	if i == nil {
		return InstanceStatus("")
	}
	return i.Status
}

func (i *InstanceResponse) GetInstanceSku() optionalnullable.OptionalNullable[InstanceSkuSummary] {
	if i == nil {
		return nil
	}
	return i.InstanceSku
}

func (i *InstanceResponse) GetCapacity() CapacitySummary {
	if i == nil {
		return CapacitySummary{}
	}
	return i.Capacity
}

func (i *InstanceResponse) GetPool() PoolSummary {
	if i == nil {
		return PoolSummary{}
	}
	return i.Pool
}

func (i *InstanceResponse) GetCreatedAt() int64 {
	if i == nil {
		return 0
	}
	return i.CreatedAt
}

func (i *InstanceResponse) GetImage() ImageSummary {
	if i == nil {
		return ImageSummary{}
	}
	return i.Image
}

func (i *InstanceResponse) GetDeployment() optionalnullable.OptionalNullable[DeploymentSummary] {
	if i == nil {
		return nil
	}
	return i.Deployment
}

func (i *InstanceResponse) GetCloudInitUserDataUsed() bool {
	if i == nil {
		return false
	}
	return i.CloudInitUserDataUsed
}

func (i *InstanceResponse) GetCloudInitUserData() *string {
	if i == nil {
		return nil
	}
	return i.CloudInitUserData
}

func (i *InstanceResponse) GetTags() optionalnullable.OptionalNullable[map[string]string] {
	if i == nil {
		return nil
	}
	return i.Tags
}

func (i *InstanceResponse) GetExpectedShutdownAt() optionalnullable.OptionalNullable[int64] {
	if i == nil {
		return nil
	}
	return i.ExpectedShutdownAt
}

func (i *InstanceResponse) GetPriorityLevel() optionalnullable.OptionalNullable[InstancePriority] {
	if i == nil {
		return nil
	}
	return i.PriorityLevel
}
