// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/types"
)

type InstanceSkuPropertyEnumeration struct {
	// A property key describing something about an instance SKU (e.g. `accelerator`).
	Key InstanceSkuPropertyKey `json:"key"`
	// One allowed value for an enumeration-typed property key.
	Value InstanceSkuEnumerationValue `json:"value"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ *string `const:"enumeration" json:"type"`
}

func (i InstanceSkuPropertyEnumeration) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InstanceSkuPropertyEnumeration) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InstanceSkuPropertyEnumeration) GetKey() InstanceSkuPropertyKey {
	if i == nil {
		return InstanceSkuPropertyKey{}
	}
	return i.Key
}

func (i *InstanceSkuPropertyEnumeration) GetValue() InstanceSkuEnumerationValue {
	if i == nil {
		return InstanceSkuEnumerationValue{}
	}
	return i.Value
}

func (i *InstanceSkuPropertyEnumeration) GetType() *string {
	return types.Pointer("enumeration")
}

type InstanceSkuPropertyType string

const (
	InstanceSkuPropertyTypeInstanceSkuPropertyEnumeration InstanceSkuPropertyType = "InstanceSkuProperty_Enumeration"
	InstanceSkuPropertyTypeUnknown                        InstanceSkuPropertyType = "Unknown"
)

// InstanceSkuProperty - A property set on an instance SKU. Tagged by `type` so new value kinds can be added without breaking clients.
type InstanceSkuProperty struct {
	InstanceSkuPropertyEnumeration *InstanceSkuPropertyEnumeration `queryParam:"inline" union:"member"`
	UnknownRaw                     json.RawMessage                 `json:"-" union:"unknown"`

	Type InstanceSkuPropertyType
}

func CreateInstanceSkuPropertyInstanceSkuPropertyEnumeration(instanceSkuPropertyEnumeration InstanceSkuPropertyEnumeration) InstanceSkuProperty {
	typ := InstanceSkuPropertyTypeInstanceSkuPropertyEnumeration

	return InstanceSkuProperty{
		InstanceSkuPropertyEnumeration: &instanceSkuPropertyEnumeration,
		Type:                           typ,
	}
}

func CreateInstanceSkuPropertyUnknown(raw json.RawMessage) InstanceSkuProperty {
	return InstanceSkuProperty{
		UnknownRaw: raw,
		Type:       InstanceSkuPropertyTypeUnknown,
	}
}

func (u InstanceSkuProperty) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u InstanceSkuProperty) IsUnknown() bool {
	return u.Type == InstanceSkuPropertyTypeUnknown
}

func (u *InstanceSkuProperty) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var instanceSkuPropertyEnumeration InstanceSkuPropertyEnumeration = InstanceSkuPropertyEnumeration{}
	if err := utils.UnmarshalJSON(data, &instanceSkuPropertyEnumeration, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InstanceSkuPropertyTypeInstanceSkuPropertyEnumeration,
			Value: &instanceSkuPropertyEnumeration,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = InstanceSkuPropertyTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = InstanceSkuPropertyTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(InstanceSkuPropertyType)
	switch best.Type {
	case InstanceSkuPropertyTypeInstanceSkuPropertyEnumeration:
		u.InstanceSkuPropertyEnumeration = best.Value.(*InstanceSkuPropertyEnumeration)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = InstanceSkuPropertyTypeUnknown
	return nil
}

func (u InstanceSkuProperty) MarshalJSON() ([]byte, error) {
	if u.InstanceSkuPropertyEnumeration != nil {
		return utils.MarshalJSON(u.InstanceSkuPropertyEnumeration, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type InstanceSkuProperty: all fields are null")
}
