// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go-sdk/internal/utils"
	"github.com/sfcompute/sfc-go-sdk/types"
)

type InternalServerErrorError struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_   *string `const:"api_error" json:"type"`
	Message string  `json:"message"`
}

func (i InternalServerErrorError) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InternalServerErrorError) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InternalServerErrorError) GetType() *string {
	return types.Pointer("api_error")
}

func (i *InternalServerErrorError) GetMessage() string {
	if i == nil {
		return ""
	}
	return i.Message
}
