// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/types"
)

type ListUserFeatureFlagsResponse struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	object  *string           `const:"list" json:"object"`
	Data    []UserFeatureFlag `json:"data"`
	HasMore bool              `json:"has_more"`
}

func (l ListUserFeatureFlagsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListUserFeatureFlagsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListUserFeatureFlagsResponse) GetObject() *string {
	return types.Pointer("list")
}

func (l *ListUserFeatureFlagsResponse) GetData() []UserFeatureFlag {
	if l == nil {
		return []UserFeatureFlag{}
	}
	return l.Data
}

func (l *ListUserFeatureFlagsResponse) GetHasMore() bool {
	if l == nil {
		return false
	}
	return l.HasMore
}
