// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/optionalnullable"
	"github.com/sfcompute/sfc-go/types"
)

type ListPoolsResponse struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	object  *string                                   `const:"list" json:"object"`
	Cursor  optionalnullable.OptionalNullable[string] `json:"cursor,omitzero"`
	HasMore bool                                      `json:"has_more"`
	Data    []PoolResponse                            `json:"data"`
}

func (l ListPoolsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListPoolsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListPoolsResponse) GetObject() *string {
	return types.Pointer("list")
}

func (l *ListPoolsResponse) GetCursor() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.Cursor
}

func (l *ListPoolsResponse) GetHasMore() bool {
	if l == nil {
		return false
	}
	return l.HasMore
}

func (l *ListPoolsResponse) GetData() []PoolResponse {
	if l == nil {
		return []PoolResponse{}
	}
	return l.Data
}
