// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/optionalnullable"
	"github.com/sfcompute/sfc-go/types"
)

// ListOrderbookFillsResponse - Paginated list of historical fills, newest first.
type ListOrderbookFillsResponse struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	object       *string             `const:"list" json:"object"`
	Requirements map[string][]string `json:"requirements"`
	// Unix timestamp.
	StartAt int64 `json:"start_at"`
	// Unix timestamp.
	EndAt int64 `json:"end_at"`
	// Unix timestamp.
	RequestedAt int64                                     `json:"requested_at"`
	Cursor      optionalnullable.OptionalNullable[string] `json:"cursor,omitzero"`
	HasMore     bool                                      `json:"has_more"`
	Data        []OrderbookFill                           `json:"data"`
}

func (l ListOrderbookFillsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOrderbookFillsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListOrderbookFillsResponse) GetObject() *string {
	return types.Pointer("list")
}

func (l *ListOrderbookFillsResponse) GetRequirements() map[string][]string {
	if l == nil {
		return map[string][]string{}
	}
	return l.Requirements
}

func (l *ListOrderbookFillsResponse) GetStartAt() int64 {
	if l == nil {
		return 0
	}
	return l.StartAt
}

func (l *ListOrderbookFillsResponse) GetEndAt() int64 {
	if l == nil {
		return 0
	}
	return l.EndAt
}

func (l *ListOrderbookFillsResponse) GetRequestedAt() int64 {
	if l == nil {
		return 0
	}
	return l.RequestedAt
}

func (l *ListOrderbookFillsResponse) GetCursor() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.Cursor
}

func (l *ListOrderbookFillsResponse) GetHasMore() bool {
	if l == nil {
		return false
	}
	return l.HasMore
}

func (l *ListOrderbookFillsResponse) GetData() []OrderbookFill {
	if l == nil {
		return []OrderbookFill{}
	}
	return l.Data
}
