// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NodeLogChunk struct {
	// Unix timestamp.
	TimestampRealtime int64 `json:"timestamp_realtime"`
	// Monotonic clock seconds.
	TimestampMonotonicSecs int64 `json:"timestamp_monotonic_secs"`
	// Nanosecond component of the monotonic clock.
	TimestampMonotonicNanos int64 `json:"timestamp_monotonic_nanos"`
	Seqnum                  int64 `json:"seqnum"`
	// Base-64 encoded raw console output.
	Data string `json:"data"`
}

func (n *NodeLogChunk) GetTimestampRealtime() int64 {
	if n == nil {
		return 0
	}
	return n.TimestampRealtime
}

func (n *NodeLogChunk) GetTimestampMonotonicSecs() int64 {
	if n == nil {
		return 0
	}
	return n.TimestampMonotonicSecs
}

func (n *NodeLogChunk) GetTimestampMonotonicNanos() int64 {
	if n == nil {
		return 0
	}
	return n.TimestampMonotonicNanos
}

func (n *NodeLogChunk) GetSeqnum() int64 {
	if n == nil {
		return 0
	}
	return n.Seqnum
}

func (n *NodeLogChunk) GetData() string {
	if n == nil {
		return ""
	}
	return n.Data
}
