// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NodeSSHHostKey struct {
	// Key algorithm.
	KeyType string `json:"key_type"`
	// Base64-encoded public key.
	Key string `json:"key"`
}

func (n *NodeSSHHostKey) GetKeyType() string {
	if n == nil {
		return ""
	}
	return n.KeyType
}

func (n *NodeSSHHostKey) GetKey() string {
	if n == nil {
		return ""
	}
	return n.Key
}
