// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// NodeStatus - `awaiting_allocation` when waiting for compute allocation on its capacity, `running` once assigned and physical node is running (still takes time for image to be downloaded and booted), `terminated` when stopped by user or after running out of allocation, `failed` on hardware fault.
type NodeStatus string

const (
	NodeStatusAwaitingAllocation NodeStatus = "awaiting_allocation"
	NodeStatusRunning            NodeStatus = "running"
	NodeStatusTerminated         NodeStatus = "terminated"
	NodeStatusFailed             NodeStatus = "failed"
)

func (e NodeStatus) ToPointer() *NodeStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *NodeStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "awaiting_allocation", "running", "terminated", "failed":
			return true
		}
	}
	return false
}
