// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/optionalnullable"
)

// OrderbookQuoteResponse - Top-of-book snapshot: the highest resting buy (`best_bid`) and lowest resting sell (`best_ask`) for the requested window. Either side may be absent if no orders are resting on it.
type OrderbookQuoteResponse struct {
	// Key/value filters on instance SKU properties.
	//
	// Valid keys and values are published at `GET /v2/instance_sku_property_catalog`.
	//
	// Empty map = no constraints.
	Requirements map[string][]string `json:"requirements"`
	// Unix timestamp.
	StartAt int64 `json:"start_at"`
	// Unix timestamp.
	EndAt int64 `json:"end_at"`
	// Unix timestamp.
	RequestedAt int64                                         `json:"requested_at"`
	BestBid     optionalnullable.OptionalNullable[PriceLevel] `json:"best_bid,omitzero"`
	BestAsk     optionalnullable.OptionalNullable[PriceLevel] `json:"best_ask,omitzero"`
}

func (o OrderbookQuoteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrderbookQuoteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrderbookQuoteResponse) GetRequirements() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Requirements
}

func (o *OrderbookQuoteResponse) GetStartAt() int64 {
	if o == nil {
		return 0
	}
	return o.StartAt
}

func (o *OrderbookQuoteResponse) GetEndAt() int64 {
	if o == nil {
		return 0
	}
	return o.EndAt
}

func (o *OrderbookQuoteResponse) GetRequestedAt() int64 {
	if o == nil {
		return 0
	}
	return o.RequestedAt
}

func (o *OrderbookQuoteResponse) GetBestBid() optionalnullable.OptionalNullable[PriceLevel] {
	if o == nil {
		return nil
	}
	return o.BestBid
}

func (o *OrderbookQuoteResponse) GetBestAsk() optionalnullable.OptionalNullable[PriceLevel] {
	if o == nil {
		return nil
	}
	return o.BestAsk
}
