// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/optionalnullable"
)

// OrderbookWindow - Summary row: one delivery window with at least one resting order matching the requested filter.
type OrderbookWindow struct {
	// Unix timestamp.
	StartAt int64 `json:"start_at"`
	// Unix timestamp.
	EndAt int64 `json:"end_at"`
	// Duration of the window in whole hours.
	DurationHours int64 `json:"duration_hours"`
	// Number of resting bid orders at this window.
	TotalBidOrderCount int64 `json:"total_bid_order_count"`
	// Number of resting ask orders at this window.
	TotalAskOrderCount int64 `json:"total_ask_order_count"`
	// Total node count across all resting bids at this window.
	TotalBidNodeCount int64 `json:"total_bid_node_count"`
	// Total node count across all resting asks at this window.
	TotalAskNodeCount int64                                         `json:"total_ask_node_count"`
	BestBid           optionalnullable.OptionalNullable[PriceLevel] `json:"best_bid,omitzero"`
	BestAsk           optionalnullable.OptionalNullable[PriceLevel] `json:"best_ask,omitzero"`
}

func (o OrderbookWindow) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrderbookWindow) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrderbookWindow) GetStartAt() int64 {
	if o == nil {
		return 0
	}
	return o.StartAt
}

func (o *OrderbookWindow) GetEndAt() int64 {
	if o == nil {
		return 0
	}
	return o.EndAt
}

func (o *OrderbookWindow) GetDurationHours() int64 {
	if o == nil {
		return 0
	}
	return o.DurationHours
}

func (o *OrderbookWindow) GetTotalBidOrderCount() int64 {
	if o == nil {
		return 0
	}
	return o.TotalBidOrderCount
}

func (o *OrderbookWindow) GetTotalAskOrderCount() int64 {
	if o == nil {
		return 0
	}
	return o.TotalAskOrderCount
}

func (o *OrderbookWindow) GetTotalBidNodeCount() int64 {
	if o == nil {
		return 0
	}
	return o.TotalBidNodeCount
}

func (o *OrderbookWindow) GetTotalAskNodeCount() int64 {
	if o == nil {
		return 0
	}
	return o.TotalAskNodeCount
}

func (o *OrderbookWindow) GetBestBid() optionalnullable.OptionalNullable[PriceLevel] {
	if o == nil {
		return nil
	}
	return o.BestBid
}

func (o *OrderbookWindow) GetBestAsk() optionalnullable.OptionalNullable[PriceLevel] {
	if o == nil {
		return nil
	}
	return o.BestAsk
}
