// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/optionalnullable"
)

type PatchInstanceRequest struct {
	Name optionalnullable.OptionalNullable[string]            `json:"name,omitzero"`
	Tags optionalnullable.OptionalNullable[map[string]string] `json:"tags,omitzero"`
	// Shutdown priority. Higher numbers are kept longer. Omit to leave unchanged.
	Priority optionalnullable.OptionalNullable[int64] `json:"priority,omitzero"`
}

func (p PatchInstanceRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatchInstanceRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PatchInstanceRequest) GetName() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PatchInstanceRequest) GetTags() optionalnullable.OptionalNullable[map[string]string] {
	if p == nil {
		return nil
	}
	return p.Tags
}

func (p *PatchInstanceRequest) GetPriority() optionalnullable.OptionalNullable[int64] {
	if p == nil {
		return nil
	}
	return p.Priority
}
