// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/types"
)

type PaymentRequiredErrorError struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_   *string `const:"payment_required" json:"type"`
	Message string  `json:"message"`
}

func (p PaymentRequiredErrorError) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaymentRequiredErrorError) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PaymentRequiredErrorError) GetType() *string {
	return types.Pointer("payment_required")
}

func (p *PaymentRequiredErrorError) GetMessage() string {
	if p == nil {
		return ""
	}
	return p.Message
}
