// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PermissionCheckResponse struct {
	// Whether the caller can perform every action in the request directly without approval.
	Allowed bool `json:"allowed"`
}

func (p *PermissionCheckResponse) GetAllowed() bool {
	if p == nil {
		return false
	}
	return p.Allowed
}
