// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PriceLevel - One price level in the order book — orders sharing the same per-node-hour rate are summed into a single entry.
type PriceLevel struct {
	// Price rate in dollars per node-hour.
	DollarsPerNodeHour string `json:"dollars_per_node_hour"`
	// Node count over time, as a list of `[start_at, end_at)` time ranges.
	//
	// Example: 5 nodes from t=0 to t=3600 is `[{"start_at": 0, "end_at": 3600, "node_count": 5}]`.
	//
	// `start_at` and `end_at` must be 60-second aligned, `node_count` must be non-negative. On non-final entries, `end_at` may be omitted (inferred from the next entry's `start_at`); gaps fill with `node_count: 0`.
	AllocationScheduleDelta []ScheduleEntry `json:"allocation_schedule_delta"`
}

func (p *PriceLevel) GetDollarsPerNodeHour() string {
	if p == nil {
		return ""
	}
	return p.DollarsPerNodeHour
}

func (p *PriceLevel) GetAllocationScheduleDelta() []ScheduleEntry {
	if p == nil {
		return []ScheduleEntry{}
	}
	return p.AllocationScheduleDelta
}
