// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/types"
)

type ProcurementResponse struct {
	ID string `json:"id"`
	// A resource path for a procurement resource. Format: sfc:procurement:<account>:<workspace>:<name>.
	ResourcePath string `json:"resource_path"`
	Owner        string `json:"owner"`
	Workspace    string `json:"workspace"`
	Name         string `json:"name"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	object *string           `const:"procurement" json:"object"`
	Target ProcurementTarget `json:"target"`
	// ID (default) or expanded summary when using expand parameter
	Capacity ExpandableCapacityIDCapacitySummaryUnion `json:"capacity"`
	// Price rate in dollars per node-hour.
	MinSellPriceDollarsPerNodeHour string `json:"min_sell_price_dollars_per_node_hour"`
	// Price rate in dollars per node-hour.
	MaxBuyPriceDollarsPerNodeHour string `json:"max_buy_price_dollars_per_node_hour"`
	// How far ahead (in minutes) the procurement buys and sells compute. Higher values secure compute further in advance but commit to longer windows that may need to be sold when scaling down, potentially at a loss. Lower values reduce waste but risk compute being unavailable. Orders are placed in 1-hour blocks, so the furthest hour is secured up to `managed_window_minutes - 60` minutes before it begins.
	ManagedWindowMinutes int `json:"managed_window_minutes"`
	// Enable/disable the procurement. Disabling cancels all standing orders.
	Enabled bool                 `json:"enabled"`
	Status  ReconciliationStatus `json:"status"`
	// Unix timestamp.
	CreatedAt int64 `json:"created_at"`
	// Unix timestamp.
	UpdatedAt int64 `json:"updated_at"`
}

func (p ProcurementResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProcurementResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *ProcurementResponse) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *ProcurementResponse) GetResourcePath() string {
	if p == nil {
		return ""
	}
	return p.ResourcePath
}

func (p *ProcurementResponse) GetOwner() string {
	if p == nil {
		return ""
	}
	return p.Owner
}

func (p *ProcurementResponse) GetWorkspace() string {
	if p == nil {
		return ""
	}
	return p.Workspace
}

func (p *ProcurementResponse) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *ProcurementResponse) GetObject() *string {
	return types.Pointer("procurement")
}

func (p *ProcurementResponse) GetTarget() ProcurementTarget {
	if p == nil {
		return ProcurementTarget{}
	}
	return p.Target
}

func (p *ProcurementResponse) GetCapacity() ExpandableCapacityIDCapacitySummaryUnion {
	if p == nil {
		return ExpandableCapacityIDCapacitySummaryUnion{}
	}
	return p.Capacity
}

func (p *ProcurementResponse) GetMinSellPriceDollarsPerNodeHour() string {
	if p == nil {
		return ""
	}
	return p.MinSellPriceDollarsPerNodeHour
}

func (p *ProcurementResponse) GetMaxBuyPriceDollarsPerNodeHour() string {
	if p == nil {
		return ""
	}
	return p.MaxBuyPriceDollarsPerNodeHour
}

func (p *ProcurementResponse) GetManagedWindowMinutes() int {
	if p == nil {
		return 0
	}
	return p.ManagedWindowMinutes
}

func (p *ProcurementResponse) GetEnabled() bool {
	if p == nil {
		return false
	}
	return p.Enabled
}

func (p *ProcurementResponse) GetStatus() ReconciliationStatus {
	if p == nil {
		return ReconciliationStatus{}
	}
	return p.Status
}

func (p *ProcurementResponse) GetCreatedAt() int64 {
	if p == nil {
		return 0
	}
	return p.CreatedAt
}

func (p *ProcurementResponse) GetUpdatedAt() int64 {
	if p == nil {
		return 0
	}
	return p.UpdatedAt
}
