// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"github.com/sfcompute/sfc-go-sdk/internal/utils"
)

type ProcurementTargetType string

const (
	ProcurementTargetTypeNodeCountTag ProcurementTargetType = "NodeCountTag"
	ProcurementTargetTypeInteger      ProcurementTargetType = "integer"
	ProcurementTargetTypeUnknown      ProcurementTargetType = "Unknown"
)

type ProcurementTarget struct {
	NodeCountTag *string         `queryParam:"inline" union:"member"`
	Integer      *int64          `queryParam:"inline" union:"member"`
	UnknownRaw   json.RawMessage `json:"-" union:"unknown"`

	Type ProcurementTargetType
}

func CreateProcurementTargetNodeCountTag(nodeCountTag string) ProcurementTarget {
	typ := ProcurementTargetTypeNodeCountTag

	return ProcurementTarget{
		NodeCountTag: &nodeCountTag,
		Type:         typ,
	}
}

func CreateProcurementTargetInteger(integer int64) ProcurementTarget {
	typ := ProcurementTargetTypeInteger

	return ProcurementTarget{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateProcurementTargetUnknown(raw json.RawMessage) ProcurementTarget {
	return ProcurementTarget{
		UnknownRaw: raw,
		Type:       ProcurementTargetTypeUnknown,
	}
}

func (u ProcurementTarget) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u ProcurementTarget) IsUnknown() bool {
	return u.Type == ProcurementTargetTypeUnknown
}

func (u *ProcurementTarget) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var nodeCountTag string = ""
	if err := utils.UnmarshalJSON(data, &nodeCountTag, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ProcurementTargetTypeNodeCountTag,
			Value: &nodeCountTag,
		})
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ProcurementTargetTypeInteger,
			Value: &integer,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ProcurementTargetTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ProcurementTargetTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ProcurementTargetType)
	switch best.Type {
	case ProcurementTargetTypeNodeCountTag:
		u.NodeCountTag = best.Value.(*string)
		return nil
	case ProcurementTargetTypeInteger:
		u.Integer = best.Value.(*int64)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = ProcurementTargetTypeUnknown
	return nil
}

func (u ProcurementTarget) MarshalJSON() ([]byte, error) {
	if u.NodeCountTag != nil {
		return utils.MarshalJSON(u.NodeCountTag, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type ProcurementTarget: all fields are null")
}
