// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SetEnrollmentRequest struct {
	Enrolled bool `json:"enrolled"`
}

func (s *SetEnrollmentRequest) GetEnrolled() bool {
	if s == nil {
		return false
	}
	return s.Enrolled
}
