// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/types"
)

type SetEnrollmentResponse struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	object      *string `const:"feature_flag" json:"object"`
	FeatureFlag string  `json:"feature_flag"`
	Enrolled    bool    `json:"enrolled"`
}

func (s SetEnrollmentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SetEnrollmentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SetEnrollmentResponse) GetObject() *string {
	return types.Pointer("feature_flag")
}

func (s *SetEnrollmentResponse) GetFeatureFlag() string {
	if s == nil {
		return ""
	}
	return s.FeatureFlag
}

func (s *SetEnrollmentResponse) GetEnrolled() bool {
	if s == nil {
		return false
	}
	return s.Enrolled
}
