// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/types"
)

type UserFeatureFlag struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	object      *string `const:"feature_flag" json:"object"`
	FeatureFlag string  `json:"feature_flag"`
	Description string  `json:"description"`
	UserEnroll  bool    `json:"user_enroll"`
	Enrolled    bool    `json:"enrolled"`
}

func (u UserFeatureFlag) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserFeatureFlag) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UserFeatureFlag) GetObject() *string {
	return types.Pointer("feature_flag")
}

func (u *UserFeatureFlag) GetFeatureFlag() string {
	if u == nil {
		return ""
	}
	return u.FeatureFlag
}

func (u *UserFeatureFlag) GetDescription() string {
	if u == nil {
		return ""
	}
	return u.Description
}

func (u *UserFeatureFlag) GetUserEnroll() bool {
	if u == nil {
		return false
	}
	return u.UserEnroll
}

func (u *UserFeatureFlag) GetEnrolled() bool {
	if u == nil {
		return false
	}
	return u.Enrolled
}
