// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/types"
)

type UserResponse struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	object *string `const:"user" json:"object"`
	ID     string  `json:"id"`
	// A resource path for a user resource. Format: sfc:user:<name>.
	ResourcePath string `json:"resource_path"`
	// Unix timestamp.
	CreatedAt int64 `json:"created_at"`
}

func (u UserResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UserResponse) GetObject() *string {
	return types.Pointer("user")
}

func (u *UserResponse) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UserResponse) GetResourcePath() string {
	if u == nil {
		return ""
	}
	return u.ResourcePath
}

func (u *UserResponse) GetCreatedAt() int64 {
	if u == nil {
		return 0
	}
	return u.CreatedAt
}
