// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/optionalnullable"
	"github.com/sfcompute/sfc-go/types"
)

type V2CapacityTransferResponse struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	object *string                `const:"capacity_transfer" json:"object"`
	ID     string                 `json:"id"`
	Status CapacityTransferStatus `json:"status"`
	// Unix timestamp.
	CreatedAt    int64  `json:"created_at"`
	FromCapacity string `json:"from_capacity"`
	ToCapacity   string `json:"to_capacity"`
	// Summary view of an instance SKU embedded on responses that reference one (orders, procurements, instances, capacity transfers). Carries both the id and the human-readable name. Legacy SKUs whose `name` column hasn't been backfilled use `UNKNOWN_INSTANCE_SKU_NAME` as a placeholder so this field is always populated on the wire.
	InstanceSku InstanceSkuSummary `json:"instance_sku"`
	// Reason a capacity transfer was rejected.
	RejectedReason optionalnullable.OptionalNullable[string] `json:"rejected_reason,omitzero"`
	// Node count over time, as a list of `[start_at, end_at)` time ranges.
	//
	// Example: 5 nodes from t=0 to t=3600 is `[{"start_at": 0, "end_at": 3600, "node_count": 5}]`.
	//
	// `start_at` and `end_at` must be 60-second aligned, `node_count` must be non-negative. On non-final entries, `end_at` may be omitted (inferred from the next entry's `start_at`); gaps fill with `node_count: 0`.
	AllocationScheduleDelta []ScheduleEntry `json:"allocation_schedule_delta"`
}

func (v V2CapacityTransferResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2CapacityTransferResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2CapacityTransferResponse) GetObject() *string {
	return types.Pointer("capacity_transfer")
}

func (v *V2CapacityTransferResponse) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V2CapacityTransferResponse) GetStatus() CapacityTransferStatus {
	if v == nil {
		return CapacityTransferStatus("")
	}
	return v.Status
}

func (v *V2CapacityTransferResponse) GetCreatedAt() int64 {
	if v == nil {
		return 0
	}
	return v.CreatedAt
}

func (v *V2CapacityTransferResponse) GetFromCapacity() string {
	if v == nil {
		return ""
	}
	return v.FromCapacity
}

func (v *V2CapacityTransferResponse) GetToCapacity() string {
	if v == nil {
		return ""
	}
	return v.ToCapacity
}

func (v *V2CapacityTransferResponse) GetInstanceSku() InstanceSkuSummary {
	if v == nil {
		return InstanceSkuSummary{}
	}
	return v.InstanceSku
}

func (v *V2CapacityTransferResponse) GetRejectedReason() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.RejectedReason
}

func (v *V2CapacityTransferResponse) GetAllocationScheduleDelta() []ScheduleEntry {
	if v == nil {
		return []ScheduleEntry{}
	}
	return v.AllocationScheduleDelta
}

// #region class-body-v2capacitytransferresponse
// #endregion class-body-v2capacitytransferresponse
