// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2CreatePoolTransferRequest - Transfer some or all of one pool into another.
type V2CreatePoolTransferRequest struct {
	// A resource path like 'sfc:pool:acme:prod:my-pool' _or_ an ID. Resource paths are human-readable but not stable - they change when resources are renamed or moved. IDs are stable and permanent.
	FromPool string `json:"from_pool"`
	// A resource path like 'sfc:pool:acme:prod:my-pool' _or_ an ID. Resource paths are human-readable but not stable - they change when resources are renamed or moved. IDs are stable and permanent.
	ToPool string `json:"to_pool"`
	// Node count over time, as a list of `[start_at, end_at)` time ranges.
	//
	// Example: 5 nodes from t=0 to t=3600 is `[{"start_at": 0, "end_at": 3600, "node_count": 5}]`.
	//
	// `start_at` and `end_at` must be 60-second aligned, `node_count` must be non-negative. On non-final entries, `end_at` may be omitted (inferred from the next entry's `start_at`); gaps fill with `node_count: 0`.
	AllocationScheduleDelta []ScheduleEntry `json:"allocation_schedule_delta"`
	// Accepts the canonical prefix below; additional legacy prefixes are aliased for read compatibility. Writes always emit the canonical form.
	InstanceSku string `json:"instance_sku"`
}

func (v *V2CreatePoolTransferRequest) GetFromPool() string {
	if v == nil {
		return ""
	}
	return v.FromPool
}

func (v *V2CreatePoolTransferRequest) GetToPool() string {
	if v == nil {
		return ""
	}
	return v.ToPool
}

func (v *V2CreatePoolTransferRequest) GetAllocationScheduleDelta() []ScheduleEntry {
	if v == nil {
		return []ScheduleEntry{}
	}
	return v.AllocationScheduleDelta
}

func (v *V2CreatePoolTransferRequest) GetInstanceSku() string {
	if v == nil {
		return ""
	}
	return v.InstanceSku
}

// #region class-body-v2createpooltransferrequest
// #endregion class-body-v2createpooltransferrequest
