// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
)

// V2OrderPreviewFee - Fee charged on fills for the targeted instance SKU.
//
// Total fee = `flat_dollars_per_node_hour × node_count × duration_hours` + `percentage_bps / 10000 × execution_total_dollars`.
//
// Recomputed against the realized price at fill time.
type V2OrderPreviewFee struct {
	// Price rate in dollars per node-hour.
	FlatDollarsPerNodeHour string `json:"flat_dollars_per_node_hour"`
	// Percentage of execution total, in basis points (10000 = 100%).
	PercentageBps int `json:"percentage_bps"`
}

func (v V2OrderPreviewFee) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2OrderPreviewFee) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2OrderPreviewFee) GetFlatDollarsPerNodeHour() string {
	if v == nil {
		return ""
	}
	return v.FlatDollarsPerNodeHour
}

func (v *V2OrderPreviewFee) GetPercentageBps() int {
	if v == nil {
		return 0
	}
	return v.PercentageBps
}

// #region class-body-v2orderpreviewfee
// #endregion class-body-v2orderpreviewfee
