// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/types"
)

type V2OrderEstimateResponseUnavailable struct {
	Reason V2OrderEstimateUnavailableReason `json:"reason"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ *string `const:"unavailable" json:"type"`
}

func (v V2OrderEstimateResponseUnavailable) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2OrderEstimateResponseUnavailable) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2OrderEstimateResponseUnavailable) GetReason() V2OrderEstimateUnavailableReason {
	if v == nil {
		return V2OrderEstimateUnavailableReason("")
	}
	return v.Reason
}

func (v *V2OrderEstimateResponseUnavailable) GetType() *string {
	return types.Pointer("unavailable")
}

// #region class-body-v2orderestimateresponseunavailable
// #endregion class-body-v2orderestimateresponseunavailable

type V2OrderEstimateResponseSuccess struct {
	Order V2OrderProposal `json:"order"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ *string `const:"success" json:"type"`
}

func (v V2OrderEstimateResponseSuccess) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2OrderEstimateResponseSuccess) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2OrderEstimateResponseSuccess) GetOrder() V2OrderProposal {
	if v == nil {
		return V2OrderProposal{}
	}
	return v.Order
}

func (v *V2OrderEstimateResponseSuccess) GetType() *string {
	return types.Pointer("success")
}

// #region class-body-v2orderestimateresponsesuccess
// #endregion class-body-v2orderestimateresponsesuccess

type V2OrderEstimateResponseType string

const (
	V2OrderEstimateResponseTypeV2OrderEstimateResponseSuccess     V2OrderEstimateResponseType = "v2.OrderEstimateResponse_Success"
	V2OrderEstimateResponseTypeV2OrderEstimateResponseUnavailable V2OrderEstimateResponseType = "v2.OrderEstimateResponse_Unavailable"
	V2OrderEstimateResponseTypeUnknown                            V2OrderEstimateResponseType = "Unknown"
)

type V2OrderEstimateResponse struct {
	V2OrderEstimateResponseSuccess     *V2OrderEstimateResponseSuccess     `queryParam:"inline" union:"member"`
	V2OrderEstimateResponseUnavailable *V2OrderEstimateResponseUnavailable `queryParam:"inline" union:"member"`
	UnknownRaw                         json.RawMessage                     `json:"-" union:"unknown"`

	Type V2OrderEstimateResponseType
}

func CreateV2OrderEstimateResponseV2OrderEstimateResponseSuccess(v2OrderEstimateResponseSuccess V2OrderEstimateResponseSuccess) V2OrderEstimateResponse {
	typ := V2OrderEstimateResponseTypeV2OrderEstimateResponseSuccess

	return V2OrderEstimateResponse{
		V2OrderEstimateResponseSuccess: &v2OrderEstimateResponseSuccess,
		Type:                           typ,
	}
}

func CreateV2OrderEstimateResponseV2OrderEstimateResponseUnavailable(v2OrderEstimateResponseUnavailable V2OrderEstimateResponseUnavailable) V2OrderEstimateResponse {
	typ := V2OrderEstimateResponseTypeV2OrderEstimateResponseUnavailable

	return V2OrderEstimateResponse{
		V2OrderEstimateResponseUnavailable: &v2OrderEstimateResponseUnavailable,
		Type:                               typ,
	}
}

func CreateV2OrderEstimateResponseUnknown(raw json.RawMessage) V2OrderEstimateResponse {
	return V2OrderEstimateResponse{
		UnknownRaw: raw,
		Type:       V2OrderEstimateResponseTypeUnknown,
	}
}

func (u V2OrderEstimateResponse) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u V2OrderEstimateResponse) IsUnknown() bool {
	return u.Type == V2OrderEstimateResponseTypeUnknown
}

func (u *V2OrderEstimateResponse) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var v2OrderEstimateResponseSuccess V2OrderEstimateResponseSuccess = V2OrderEstimateResponseSuccess{}
	if err := utils.UnmarshalJSON(data, &v2OrderEstimateResponseSuccess, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  V2OrderEstimateResponseTypeV2OrderEstimateResponseSuccess,
			Value: &v2OrderEstimateResponseSuccess,
		})
	}

	var v2OrderEstimateResponseUnavailable V2OrderEstimateResponseUnavailable = V2OrderEstimateResponseUnavailable{}
	if err := utils.UnmarshalJSON(data, &v2OrderEstimateResponseUnavailable, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  V2OrderEstimateResponseTypeV2OrderEstimateResponseUnavailable,
			Value: &v2OrderEstimateResponseUnavailable,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = V2OrderEstimateResponseTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = V2OrderEstimateResponseTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(V2OrderEstimateResponseType)
	switch best.Type {
	case V2OrderEstimateResponseTypeV2OrderEstimateResponseSuccess:
		u.V2OrderEstimateResponseSuccess = best.Value.(*V2OrderEstimateResponseSuccess)
		return nil
	case V2OrderEstimateResponseTypeV2OrderEstimateResponseUnavailable:
		u.V2OrderEstimateResponseUnavailable = best.Value.(*V2OrderEstimateResponseUnavailable)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = V2OrderEstimateResponseTypeUnknown
	return nil
}

func (u V2OrderEstimateResponse) MarshalJSON() ([]byte, error) {
	if u.V2OrderEstimateResponseSuccess != nil {
		return utils.MarshalJSON(u.V2OrderEstimateResponseSuccess, "", true)
	}

	if u.V2OrderEstimateResponseUnavailable != nil {
		return utils.MarshalJSON(u.V2OrderEstimateResponseUnavailable, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type V2OrderEstimateResponse: all fields are null")
}
