// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/optionalnullable"
)

// V2OrderFill - A single fill event: one contract that was produced when the order matched.
type V2OrderFill struct {
	Contract optionalnullable.OptionalNullable[string] `json:"contract,omitzero"`
	// Unix timestamp.
	FilledAt int64 `json:"filled_at"`
	// Node count over time, as a list of `[start_at, end_at)` time ranges.
	//
	// Example: 5 nodes from t=0 to t=3600 is `[{"start_at": 0, "end_at": 3600, "node_count": 5}]`.
	//
	// `start_at` and `end_at` must be 60-second aligned, `node_count` must be non-negative. On non-final entries, `end_at` may be omitted (inferred from the next entry's `start_at`); gaps fill with `node_count: 0`.
	AllocationScheduleDelta []ScheduleEntry `json:"allocation_schedule_delta"`
	// Price rate in dollars per node-hour.
	PriceDollarsPerNodeHour string `json:"price_dollars_per_node_hour"`
}

func (v *V2OrderFill) GetContract() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.Contract
}

func (v *V2OrderFill) GetFilledAt() int64 {
	if v == nil {
		return 0
	}
	return v.FilledAt
}

func (v *V2OrderFill) GetAllocationScheduleDelta() []ScheduleEntry {
	if v == nil {
		return []ScheduleEntry{}
	}
	return v.AllocationScheduleDelta
}

func (v *V2OrderFill) GetPriceDollarsPerNodeHour() string {
	if v == nil {
		return ""
	}
	return v.PriceDollarsPerNodeHour
}

// #region class-body-v2orderfill
// #endregion class-body-v2orderfill
