// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type V2OrderSortBy string

const (
	V2OrderSortByCreatedAt      V2OrderSortBy = "created_at"
	V2OrderSortByMinusCreatedAt V2OrderSortBy = "-created_at"
	V2OrderSortByStartAt        V2OrderSortBy = "start_at"
	V2OrderSortByMinusStartAt   V2OrderSortBy = "-start_at"
)

func (e V2OrderSortBy) ToPointer() *V2OrderSortBy {
	return &e
}
func (e *V2OrderSortBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "start_at":
		fallthrough
	case "-start_at":
		*e = V2OrderSortBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V2OrderSortBy: %v", v)
	}
}
