// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
)

type V2OrderProposal struct {
	Body V2CreateOrderRequest `json:"body"`
	// Non-negative dollar amount.
	TotalFeeDollars string `json:"total_fee_dollars"`
	// Maintenance windows on the matched instance SKU overlapping the order's delivery window.
	Notices []V2OrderEstimateNotice `json:"notices"`
}

func (v V2OrderProposal) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2OrderProposal) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2OrderProposal) GetBody() V2CreateOrderRequest {
	if v == nil {
		return V2CreateOrderRequest{}
	}
	return v.Body
}

func (v *V2OrderProposal) GetTotalFeeDollars() string {
	if v == nil {
		return ""
	}
	return v.TotalFeeDollars
}

func (v *V2OrderProposal) GetNotices() []V2OrderEstimateNotice {
	if v == nil {
		return []V2OrderEstimateNotice{}
	}
	return v.Notices
}

// #region class-body-v2orderproposal
// #endregion class-body-v2orderproposal
