// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/optionalnullable"
)

// V2PatchPoolRequest - Update a pool. Omitted fields are left unchanged.
type V2PatchPoolRequest struct {
	Name optionalnullable.OptionalNullable[string]            `json:"name,omitzero"`
	Tags optionalnullable.OptionalNullable[map[string]string] `json:"tags,omitzero"`
}

func (v V2PatchPoolRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2PatchPoolRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2PatchPoolRequest) GetName() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *V2PatchPoolRequest) GetTags() optionalnullable.OptionalNullable[map[string]string] {
	if v == nil {
		return nil
	}
	return v.Tags
}

// #region class-body-v2patchpoolrequest
// #endregion class-body-v2patchpoolrequest
