// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/sfcompute/sfc-go/internal/utils"
	"github.com/sfcompute/sfc-go/optionalnullable"
	"github.com/sfcompute/sfc-go/types"
)

// V2PoolTransferResponse - A transfer of compute from one pool (`from_pool`) to another (`to_pool`).
type V2PoolTransferResponse struct {
	// Discriminator for `/pool_transfers` responses.
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	object *string `const:"pool_transfer" json:"object"`
	// Accepts the canonical prefix below; additional legacy prefixes are aliased for read compatibility. Writes always emit the canonical form.
	ID string `json:"id"`
	// Lifecycle status of a pool transfer.
	Status V2PoolTransferStatus `json:"status"`
	// Unix timestamp.
	CreatedAt int64  `json:"created_at"`
	FromPool  string `json:"from_pool"`
	ToPool    string `json:"to_pool"`
	// A summary of an instance SKU - its `id` and human-recognizable `alias` - embedded on resources that reference a SKU.
	InstanceSku InstanceSkuSummary `json:"instance_sku"`
	// Reason a pool transfer was rejected.
	RejectedReason optionalnullable.OptionalNullable[string] `json:"rejected_reason,omitzero"`
	// Node count over time, as a list of `[start_at, end_at)` time ranges.
	//
	// Example: 5 nodes from t=0 to t=3600 is `[{"start_at": 0, "end_at": 3600, "node_count": 5}]`.
	//
	// `start_at` and `end_at` must be 60-second aligned, `node_count` must be non-negative. On non-final entries, `end_at` may be omitted (inferred from the next entry's `start_at`); gaps fill with `node_count: 0`.
	AllocationScheduleDelta []ScheduleEntry `json:"allocation_schedule_delta"`
}

func (v V2PoolTransferResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2PoolTransferResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2PoolTransferResponse) GetObject() *string {
	return types.Pointer("pool_transfer")
}

func (v *V2PoolTransferResponse) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V2PoolTransferResponse) GetStatus() V2PoolTransferStatus {
	if v == nil {
		return V2PoolTransferStatus("")
	}
	return v.Status
}

func (v *V2PoolTransferResponse) GetCreatedAt() int64 {
	if v == nil {
		return 0
	}
	return v.CreatedAt
}

func (v *V2PoolTransferResponse) GetFromPool() string {
	if v == nil {
		return ""
	}
	return v.FromPool
}

func (v *V2PoolTransferResponse) GetToPool() string {
	if v == nil {
		return ""
	}
	return v.ToPool
}

func (v *V2PoolTransferResponse) GetInstanceSku() InstanceSkuSummary {
	if v == nil {
		return InstanceSkuSummary{}
	}
	return v.InstanceSku
}

func (v *V2PoolTransferResponse) GetRejectedReason() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.RejectedReason
}

func (v *V2PoolTransferResponse) GetAllocationScheduleDelta() []ScheduleEntry {
	if v == nil {
		return []ScheduleEntry{}
	}
	return v.AllocationScheduleDelta
}

// #region class-body-v2pooltransferresponse
// #endregion class-body-v2pooltransferresponse
