// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/sfcompute/sfc-go/models/components"
)

type ForbiddenError struct {
	Error_   components.ForbiddenErrorError `json:"error"`
	HTTPMeta components.HTTPMetadata        `json:"-"`
}

var _ error = &ForbiddenError{}

func (e *ForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
