// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/sfcompute/sfc-go/models/components"
)

type NotFoundError struct {
	Error_   components.NotFoundErrorError `json:"error"`
	HTTPMeta components.HTTPMetadata       `json:"-"`
}

var _ error = &NotFoundError{}

func (e *NotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
