// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/sfcompute/sfc-go/models/components"
)

type ServiceUnavailableError struct {
	Error_   components.ServiceUnavailableErrorError `json:"error"`
	HTTPMeta components.HTTPMetadata                 `json:"-"`
}

var _ error = &ServiceUnavailableError{}

func (e *ServiceUnavailableError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
