workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    sfc-api:
        inputs:
            - location: /Users/andreaanez/Documents/sf_compute/sfcompute/blueprint/current/openapi.json
        overlays:
            - location: .speakeasy/overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/the-san-francisco-compute-company/v2/sfc-api
targets:
    sfc-go:
        target: go
        source: sfc-api
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/the-san-francisco-compute-company/v2/sfc-api-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
